/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const PlanType = IDL.Variant({
  'monthly' : IDL.Null,
  'weekly' : IDL.Null,
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'quantityInStock' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const Time = IDL.Int;
export const OrderItem = IDL.Record({
  'saladName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'deliveryType' : IDL.Variant({ 'scheduled' : Time, 'instant' : IDL.Null }),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Subscription = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
  'saladsRemaining' : IDL.Nat,
  'user' : IDL.Principal,
  'planType' : IDL.Variant({ 'monthly' : IDL.Null, 'weekly' : IDL.Null }),
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'heightCm' : IDL.Nat,
  'dietaryPreferences' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'weightKg' : IDL.Nat,
  'dietaryRestrictions' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const MenuItemIngredient = IDL.Record({
  'menuItemName' : IDL.Text,
  'ingredientId' : IDL.Nat,
  'quantityPerOrder' : IDL.Nat,
});
export const DeliveryType = IDL.Variant({
  'scheduled' : Time,
  'instant' : IDL.Null,
});

export const MenuItemIDL = IDL.Record({
  'id' : IDL.Nat,
  'name' : IDL.Text,
  'price' : IDL.Nat,
  'calories' : IDL.Nat,
  'protein' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'tags' : IDL.Vec(IDL.Text),
  'enabled' : IDL.Bool,
});

export const idlService = IDL.Service({
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addIngredient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createSubscription' : IDL.Func([PlanType], [], []),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'principal' : IDL.Principal, 'profile' : UserProfile })
        ),
      ],
      ['query'],
    ),
  'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getMenuItemIngredients' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItemIngredient)],
      ['query'],
    ),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkIngredientToMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'placeOrder' : IDL.Func([IDL.Vec(OrderItem), IDL.Nat, DeliveryType], [], []),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'updateIngredientStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateSubscriptionStatus' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
  'claimFirstAdminRole' : IDL.Func([], [], []),
  'hasAdminBeenClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItemIDL)], ['query']),
  'addMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)], [IDL.Nat], []),
  'updateMenuItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'toggleMenuItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const PlanType = IDL.Variant({ 'monthly' : IDL.Null, 'weekly' : IDL.Null });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'quantityInStock' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const Time = IDL.Int;
  const OrderItem = IDL.Record({
    'saladName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'deliveryType' : IDL.Variant({ 'scheduled' : Time, 'instant' : IDL.Null }),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Subscription = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
    'saladsRemaining' : IDL.Nat,
    'user' : IDL.Principal,
    'planType' : IDL.Variant({ 'monthly' : IDL.Null, 'weekly' : IDL.Null }),
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'heightCm' : IDL.Nat,
    'dietaryPreferences' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'weightKg' : IDL.Nat,
    'dietaryRestrictions' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const MenuItemIngredient = IDL.Record({
    'menuItemName' : IDL.Text,
    'ingredientId' : IDL.Nat,
    'quantityPerOrder' : IDL.Nat,
  });
  const DeliveryType = IDL.Variant({
    'scheduled' : Time,
    'instant' : IDL.Null,
  });
  
  const LeadStatus = IDL.Variant({
    'new_' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
    'date' : Time,
    'status' : LeadStatus,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'name' : IDL.Text,
    'price' : IDL.Nat,
    'calories' : IDL.Nat,
    'protein' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'tags' : IDL.Vec(IDL.Text),
    'enabled' : IDL.Bool,
  });
  const DiscountType = IDL.Variant({
    'percentage' : IDL.Null,
    'flat' : IDL.Null,
  });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'discountValue' : IDL.Nat,
    'expiryDate' : IDL.Int,
    'isActive' : IDL.Bool,
  });

  const DeliveryStatus = IDL.Variant({
    'preparing': IDL.Null,
    'ready': IDL.Null,
    'outForDelivery': IDL.Null,
    'delivered': IDL.Null,
  });
  const Rider = IDL.Record({
    'id': IDL.Nat,
    'name': IDL.Text,
    'mobile': IDL.Text,
    'area': IDL.Text,
  });
  const DeliveryRecord = IDL.Record({
    'id': IDL.Nat,
    'orderId': IDL.Nat,
    'customerName': IDL.Text,
    'address': IDL.Text,
    'deliveryTime': IDL.Int,
    'status': DeliveryStatus,
    'riderId': IDL.Opt(IDL.Nat),
    'notes': IDL.Text,
  });
    return IDL.Service({
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createSubscription' : IDL.Func([PlanType], [], []),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Principal, 'profile' : UserProfile })
          ),
        ],
        ['query'],
      ),
    'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getMenuItemIngredients' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItemIngredient)],
        ['query'],
      ),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkIngredientToMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Nat, DeliveryType],
        [],
        [],
      ),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'updateIngredientStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateSubscriptionStatus' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'saveLead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'getAllLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [], []),
  'claimFirstAdminRole' : IDL.Func([], [], []),
  'hasAdminBeenClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'addMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)], [IDL.Nat], []),
    'updateMenuItem' : IDL.Func([IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Vec(IDL.Text), IDL.Vec(IDL.Text)], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'toggleMenuItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'createCoupon' : IDL.Func([IDL.Text, DiscountType, IDL.Nat, IDL.Int], [IDL.Nat], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
    'toggleCoupon' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [Coupon], ['query']),
    'addRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'updateRider' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'deleteRider' : IDL.Func([IDL.Nat], [], []),
    'getAllRiders' : IDL.Func([], [IDL.Vec(Rider)], ['query']),
    'createDelivery' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Int, IDL.Text], [IDL.Nat], []),
    'updateDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
    'assignRider' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'bulkAssignRider' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [], []),
    'updateDeliveryNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'getAllDeliveries' : IDL.Func([], [IDL.Vec(DeliveryRecord)], ['query']),
    'setUserVip' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'addUserNote' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'deleteUserNote' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getUserMeta' : IDL.Func([IDL.Principal], [IDL.Record({'isVip': IDL.Bool, 'notes': IDL.Vec(IDL.Record({'id': IDL.Nat, 'text': IDL.Text, 'createdAt': IDL.Int}))})], ['query']),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'updateUserProfileByAdmin' : IDL.Func([IDL.Principal, IDL.Record({'name': IDL.Text, 'mobile': IDL.Text, 'email': IDL.Text, 'address': IDL.Text, 'heightCm': IDL.Nat, 'weightKg': IDL.Nat, 'age': IDL.Nat, 'dietaryPreferences': IDL.Vec(IDL.Text), 'dietaryRestrictions': IDL.Vec(IDL.Text)})], [], []),

  });
};

export const init = ({ IDL }) => { return []; };