/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const BowlSize = IDL.Record({
  'calories' : IDL.Nat,
  'size' : IDL.Text,
  'price' : IDL.Nat,
  'protein' : IDL.Nat,
});
export const LinkedIngredient = IDL.Record({
  'quantityGrams' : IDL.Nat,
  'ingredientId' : IDL.Nat,
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const DiscountType = IDL.Variant({
  'flat' : IDL.Null,
  'percentage' : IDL.Null,
});
export const Time = IDL.Int;
export const ReviewStatus = IDL.Variant({
  'pending' : IDL.Null,
  'approved' : IDL.Null,
  'rejected' : IDL.Null,
});
export const Review = IDL.Record({
  'id' : IDL.Text,
  'status' : ReviewStatus,
  'userName' : IDL.Text,
  'date' : IDL.Int,
  'comment' : IDL.Text,
  'rating' : IDL.Nat,
});
export const Result = IDL.Variant({ 'ok' : Review, 'err' : IDL.Text });
export const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
export const Coupon = IDL.Record({
  'id' : IDL.Nat,
  'discountValue' : IDL.Nat,
  'expiryDate' : Time,
  'code' : IDL.Text,
  'discountType' : DiscountType,
  'isActive' : IDL.Bool,
});
export const DeliveryStatus = IDL.Variant({
  'preparing' : IDL.Null,
  'outForDelivery' : IDL.Null,
  'delivered' : IDL.Null,
  'ready' : IDL.Null,
});
export const DeliveryRecord = IDL.Record({
  'id' : IDL.Nat,
  'customerName' : IDL.Text,
  'status' : DeliveryStatus,
  'riderId' : IDL.Opt(IDL.Nat),
  'deliveryTime' : Time,
  'orderId' : IDL.Nat,
  'address' : IDL.Text,
  'notes' : IDL.Text,
});
export const Ingredient = IDL.Record({
  'id' : IDL.Nat,
  'lowStockThreshold' : IDL.Nat,
  'quantityInStock' : IDL.Nat,
  'name' : IDL.Text,
  'unit' : IDL.Text,
});
export const MenuItem = IDL.Record({
  'id' : IDL.Nat,
  'calories' : IDL.Nat,
  'name' : IDL.Text,
  'tags' : IDL.Vec(IDL.Text),
  'linkedIngredients' : IDL.Vec(LinkedIngredient),
  'sizes' : IDL.Vec(BowlSize),
  'enabled' : IDL.Bool,
  'imageUrl' : IDL.Text,
  'price' : IDL.Nat,
  'ingredients' : IDL.Vec(IDL.Text),
  'protein' : IDL.Nat,
});
export const OrderStatus = IDL.Variant({
  'pending' : IDL.Null,
  'delivered' : IDL.Null,
  'confirmed' : IDL.Null,
});
export const OrderItem = IDL.Record({
  'saladName' : IDL.Text,
  'quantity' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Order = IDL.Record({
  'id' : IDL.Nat,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : IDL.Principal,
  'deliveryNotes' : IDL.Text,
  'deliveryStatus' : DeliveryStatus,
  'assignedRiderId' : IDL.Opt(IDL.Nat),
  'deliveryTime' : IDL.Opt(Time),
  'deliveryType' : IDL.Variant({ 'scheduled' : Time, 'instant' : IDL.Null }),
  'totalAmount' : IDL.Nat,
  'items' : IDL.Vec(OrderItem),
});
export const Rider = IDL.Record({
  'id' : IDL.Nat,
  'area' : IDL.Text,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const SubscriptionPlan = IDL.Record({
  'id' : IDL.Nat,
  'totalMeals' : IDL.Nat,
  'name' : IDL.Text,
  'description' : IDL.Text,
  'validityDays' : IDL.Nat,
  'price' : IDL.Nat,
});
export const Subscription = IDL.Record({
  'status' : IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
  'saladsRemaining' : IDL.Nat,
  'planId' : IDL.Nat,
  'expiryDate' : Time,
  'user' : IDL.Principal,
  'planName' : IDL.Text,
  'startDate' : Time,
});
export const UserProfile = IDL.Record({
  'age' : IDL.Nat,
  'heightCm' : IDL.Nat,
  'dietaryPreferences' : IDL.Vec(IDL.Text),
  'name' : IDL.Text,
  'email' : IDL.Text,
  'weightKg' : IDL.Nat,
  'dietaryRestrictions' : IDL.Vec(IDL.Text),
  'address' : IDL.Text,
  'mobile' : IDL.Text,
});
export const LeadStatus = IDL.Variant({
  'new' : IDL.Null,
  'contacted' : IDL.Null,
  'converted' : IDL.Null,
});
export const Lead = IDL.Record({
  'id' : IDL.Nat,
  'status' : LeadStatus,
  'date' : Time,
  'name' : IDL.Text,
  'mobile' : IDL.Text,
});
export const MenuItemIngredient = IDL.Record({
  'menuItemName' : IDL.Text,
  'ingredientId' : IDL.Nat,
  'quantityPerOrder' : IDL.Nat,
});
export const UserNote = IDL.Record({
  'id' : IDL.Nat,
  'createdAt' : Time,
  'text' : IDL.Text,
});
export const UserMeta = IDL.Record({
  'notes' : IDL.Vec(UserNote),
  'isVip' : IDL.Bool,
});
export const DeliveryType = IDL.Variant({
  'scheduled' : Time,
  'instant' : IDL.Null,
});
export const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
export const Result_1 = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });

export const idlService = IDL.Service({
  '_initializeAccessControl' : IDL.Func([], [], []),
  'addIngredient' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
      [IDL.Nat],
      [],
    ),
  'addMenuItem' : IDL.Func(
      [
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(BowlSize),
        IDL.Vec(LinkedIngredient),
        IDL.Text,
      ],
      [IDL.Nat],
      [],
    ),
  'addRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
  'addUserNote' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'assignOrderRider' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'assignRider' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'bulkAssignRider' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [], []),
  'claimFirstAdminRole' : IDL.Func([], [], []),
  'createCoupon' : IDL.Func(
      [IDL.Text, DiscountType, IDL.Nat, Time],
      [IDL.Nat],
      [],
    ),
  'createDelivery' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'createLead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
  'createReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
  'createSubscription' : IDL.Func([IDL.Nat], [], []),
  'createSubscriptionPlan' : IDL.Func(
      [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [IDL.Nat],
      [],
    ),
  'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
  'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
  'deleteReview' : IDL.Func([IDL.Text], [Result_3], []),
  'deleteRider' : IDL.Func([IDL.Nat], [], []),
  'deleteSubscriptionPlan' : IDL.Func([IDL.Nat], [], []),
  'deleteUser' : IDL.Func([IDL.Principal], [], []),
  'deleteUserNote' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
  'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
  'getAllDeliveries' : IDL.Func([], [IDL.Vec(DeliveryRecord)], ['query']),
  'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
  'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getAllRiders' : IDL.Func([], [IDL.Vec(Rider)], ['query']),
  'getAllSubscriptionPlans' : IDL.Func(
      [],
      [IDL.Vec(SubscriptionPlan)],
      ['query'],
    ),
  'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
  'getAllUsers' : IDL.Func(
      [],
      [
        IDL.Vec(
          IDL.Record({ 'principal' : IDL.Principal, 'profile' : UserProfile })
        ),
      ],
      ['query'],
    ),
  'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
  'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
  'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
  'getMenuItemIngredients' : IDL.Func(
      [IDL.Text],
      [IDL.Vec(MenuItemIngredient)],
      ['query'],
    ),
  'getUserMeta' : IDL.Func([IDL.Principal], [UserMeta], ['query']),
  'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'hasAdminBeenClaimed' : IDL.Func([], [IDL.Bool], ['query']),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'linkIngredientToMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
  'placeOrder' : IDL.Func(
      [IDL.Vec(OrderItem), IDL.Nat, DeliveryType],
      [Result_2],
      [],
    ),
  'registerUser' : IDL.Func([UserProfile], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'saveUserProfile' : IDL.Func([UserProfile], [], []),
  'setUserVip' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
  'toggleCoupon' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'toggleMenuItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
  'updateDeliveryNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
  'updateIngredientStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
  'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
  'updateMenuItem' : IDL.Func(
      [
        IDL.Nat,
        IDL.Text,
        IDL.Nat,
        IDL.Nat,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Vec(BowlSize),
        IDL.Vec(LinkedIngredient),
        IDL.Text,
      ],
      [],
      [],
    ),
  'updateOrder' : IDL.Func(
      [IDL.Nat, IDL.Opt(DeliveryStatus), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
      [Result_1],
      [],
    ),
  'updateOrderDeliveryNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
  'updateOrderDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
  'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
  'updateReviewStatus' : IDL.Func([IDL.Text, ReviewStatus], [Result], []),
  'updateRider' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
  'updateSubscriptionPlan' : IDL.Func(
      [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
      [],
      [],
    ),
  'updateSubscriptionStatus' : IDL.Func(
      [
        IDL.Principal,
        IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
      ],
      [],
      [],
    ),
  'updateUserProfile' : IDL.Func([UserProfile], [], []),
  'updateUserProfileByAdmin' : IDL.Func([IDL.Principal, UserProfile], [], []),
  'validateCoupon' : IDL.Func([IDL.Text], [Coupon], ['query']),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const BowlSize = IDL.Record({
    'calories' : IDL.Nat,
    'size' : IDL.Text,
    'price' : IDL.Nat,
    'protein' : IDL.Nat,
  });
  const LinkedIngredient = IDL.Record({
    'quantityGrams' : IDL.Nat,
    'ingredientId' : IDL.Nat,
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const DiscountType = IDL.Variant({
    'flat' : IDL.Null,
    'percentage' : IDL.Null,
  });
  const Time = IDL.Int;
  const ReviewStatus = IDL.Variant({
    'pending' : IDL.Null,
    'approved' : IDL.Null,
    'rejected' : IDL.Null,
  });
  const Review = IDL.Record({
    'id' : IDL.Text,
    'status' : ReviewStatus,
    'userName' : IDL.Text,
    'date' : IDL.Int,
    'comment' : IDL.Text,
    'rating' : IDL.Nat,
  });
  const Result = IDL.Variant({ 'ok' : Review, 'err' : IDL.Text });
  const Result_3 = IDL.Variant({ 'ok' : IDL.Null, 'err' : IDL.Text });
  const Coupon = IDL.Record({
    'id' : IDL.Nat,
    'discountValue' : IDL.Nat,
    'expiryDate' : Time,
    'code' : IDL.Text,
    'discountType' : DiscountType,
    'isActive' : IDL.Bool,
  });
  const DeliveryStatus = IDL.Variant({
    'preparing' : IDL.Null,
    'outForDelivery' : IDL.Null,
    'delivered' : IDL.Null,
    'ready' : IDL.Null,
  });
  const DeliveryRecord = IDL.Record({
    'id' : IDL.Nat,
    'customerName' : IDL.Text,
    'status' : DeliveryStatus,
    'riderId' : IDL.Opt(IDL.Nat),
    'deliveryTime' : Time,
    'orderId' : IDL.Nat,
    'address' : IDL.Text,
    'notes' : IDL.Text,
  });
  const Ingredient = IDL.Record({
    'id' : IDL.Nat,
    'lowStockThreshold' : IDL.Nat,
    'quantityInStock' : IDL.Nat,
    'name' : IDL.Text,
    'unit' : IDL.Text,
  });
  const MenuItem = IDL.Record({
    'id' : IDL.Nat,
    'calories' : IDL.Nat,
    'name' : IDL.Text,
    'tags' : IDL.Vec(IDL.Text),
    'linkedIngredients' : IDL.Vec(LinkedIngredient),
    'sizes' : IDL.Vec(BowlSize),
    'enabled' : IDL.Bool,
    'imageUrl' : IDL.Text,
    'price' : IDL.Nat,
    'ingredients' : IDL.Vec(IDL.Text),
    'protein' : IDL.Nat,
  });
  const OrderStatus = IDL.Variant({
    'pending' : IDL.Null,
    'delivered' : IDL.Null,
    'confirmed' : IDL.Null,
  });
  const OrderItem = IDL.Record({
    'saladName' : IDL.Text,
    'quantity' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Order = IDL.Record({
    'id' : IDL.Nat,
    'status' : OrderStatus,
    'createdAt' : Time,
    'user' : IDL.Principal,
    'deliveryNotes' : IDL.Text,
    'deliveryStatus' : DeliveryStatus,
    'assignedRiderId' : IDL.Opt(IDL.Nat),
    'deliveryTime' : IDL.Opt(Time),
    'deliveryType' : IDL.Variant({ 'scheduled' : Time, 'instant' : IDL.Null }),
    'totalAmount' : IDL.Nat,
    'items' : IDL.Vec(OrderItem),
  });
  const Rider = IDL.Record({
    'id' : IDL.Nat,
    'area' : IDL.Text,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const SubscriptionPlan = IDL.Record({
    'id' : IDL.Nat,
    'totalMeals' : IDL.Nat,
    'name' : IDL.Text,
    'description' : IDL.Text,
    'validityDays' : IDL.Nat,
    'price' : IDL.Nat,
  });
  const Subscription = IDL.Record({
    'status' : IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
    'saladsRemaining' : IDL.Nat,
    'planId' : IDL.Nat,
    'expiryDate' : Time,
    'user' : IDL.Principal,
    'planName' : IDL.Text,
    'startDate' : Time,
  });
  const UserProfile = IDL.Record({
    'age' : IDL.Nat,
    'heightCm' : IDL.Nat,
    'dietaryPreferences' : IDL.Vec(IDL.Text),
    'name' : IDL.Text,
    'email' : IDL.Text,
    'weightKg' : IDL.Nat,
    'dietaryRestrictions' : IDL.Vec(IDL.Text),
    'address' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const LeadStatus = IDL.Variant({
    'new' : IDL.Null,
    'contacted' : IDL.Null,
    'converted' : IDL.Null,
  });
  const Lead = IDL.Record({
    'id' : IDL.Nat,
    'status' : LeadStatus,
    'date' : Time,
    'name' : IDL.Text,
    'mobile' : IDL.Text,
  });
  const MenuItemIngredient = IDL.Record({
    'menuItemName' : IDL.Text,
    'ingredientId' : IDL.Nat,
    'quantityPerOrder' : IDL.Nat,
  });
  const UserNote = IDL.Record({
    'id' : IDL.Nat,
    'createdAt' : Time,
    'text' : IDL.Text,
  });
  const UserMeta = IDL.Record({
    'notes' : IDL.Vec(UserNote),
    'isVip' : IDL.Bool,
  });
  const DeliveryType = IDL.Variant({
    'scheduled' : Time,
    'instant' : IDL.Null,
  });
  const Result_2 = IDL.Variant({ 'ok' : IDL.Nat, 'err' : IDL.Text });
  const Result_1 = IDL.Variant({ 'ok' : Order, 'err' : IDL.Text });
  
  return IDL.Service({
    '_initializeAccessControl' : IDL.Func([], [], []),
    'addIngredient' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Nat, IDL.Nat],
        [IDL.Nat],
        [],
      ),
    'addMenuItem' : IDL.Func(
        [
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(BowlSize),
          IDL.Vec(LinkedIngredient),
          IDL.Text,
        ],
        [IDL.Nat],
        [],
      ),
    'addRider' : IDL.Func([IDL.Text, IDL.Text, IDL.Text], [IDL.Nat], []),
    'addUserNote' : IDL.Func([IDL.Principal, IDL.Text], [IDL.Nat], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'assignOrderRider' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'assignRider' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'bulkAssignRider' : IDL.Func([IDL.Vec(IDL.Nat), IDL.Nat], [], []),
    'claimFirstAdminRole' : IDL.Func([], [], []),
    'createCoupon' : IDL.Func(
        [IDL.Text, DiscountType, IDL.Nat, Time],
        [IDL.Nat],
        [],
      ),
    'createDelivery' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Text, Time, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'createLead' : IDL.Func([IDL.Text, IDL.Text], [IDL.Nat], []),
    'createReview' : IDL.Func([IDL.Text, IDL.Nat, IDL.Text], [Result], []),
    'createSubscription' : IDL.Func([IDL.Nat], [], []),
    'createSubscriptionPlan' : IDL.Func(
        [IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [IDL.Nat],
        [],
      ),
    'deleteCoupon' : IDL.Func([IDL.Nat], [], []),
    'deleteMenuItem' : IDL.Func([IDL.Nat], [], []),
    'deleteReview' : IDL.Func([IDL.Text], [Result_3], []),
    'deleteRider' : IDL.Func([IDL.Nat], [], []),
    'deleteSubscriptionPlan' : IDL.Func([IDL.Nat], [], []),
    'deleteUser' : IDL.Func([IDL.Principal], [], []),
    'deleteUserNote' : IDL.Func([IDL.Principal, IDL.Nat], [], []),
    'getAllCoupons' : IDL.Func([], [IDL.Vec(Coupon)], ['query']),
    'getAllDeliveries' : IDL.Func([], [IDL.Vec(DeliveryRecord)], ['query']),
    'getAllIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getAllMenuItems' : IDL.Func([], [IDL.Vec(MenuItem)], ['query']),
    'getAllOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getAllReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getAllRiders' : IDL.Func([], [IDL.Vec(Rider)], ['query']),
    'getAllSubscriptionPlans' : IDL.Func(
        [],
        [IDL.Vec(SubscriptionPlan)],
        ['query'],
      ),
    'getAllSubscriptions' : IDL.Func([], [IDL.Vec(Subscription)], ['query']),
    'getAllUsers' : IDL.Func(
        [],
        [
          IDL.Vec(
            IDL.Record({ 'principal' : IDL.Principal, 'profile' : UserProfile })
          ),
        ],
        ['query'],
      ),
    'getApprovedReviews' : IDL.Func([], [IDL.Vec(Review)], ['query']),
    'getCallerSubscription' : IDL.Func([], [IDL.Opt(Subscription)], ['query']),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getLeads' : IDL.Func([], [IDL.Vec(Lead)], ['query']),
    'getLowStockIngredients' : IDL.Func([], [IDL.Vec(Ingredient)], ['query']),
    'getMenuItemIngredients' : IDL.Func(
        [IDL.Text],
        [IDL.Vec(MenuItemIngredient)],
        ['query'],
      ),
    'getUserMeta' : IDL.Func([IDL.Principal], [UserMeta], ['query']),
    'getUserOrders' : IDL.Func([], [IDL.Vec(Order)], ['query']),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'hasAdminBeenClaimed' : IDL.Func([], [IDL.Bool], ['query']),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'linkIngredientToMenuItem' : IDL.Func([IDL.Text, IDL.Nat, IDL.Nat], [], []),
    'placeOrder' : IDL.Func(
        [IDL.Vec(OrderItem), IDL.Nat, DeliveryType],
        [Result_2],
        [],
      ),
    'registerUser' : IDL.Func([UserProfile], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'saveUserProfile' : IDL.Func([UserProfile], [], []),
    'setUserVip' : IDL.Func([IDL.Principal, IDL.Bool], [], []),
    'toggleCoupon' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'toggleMenuItem' : IDL.Func([IDL.Nat, IDL.Bool], [], []),
    'updateDeliveryNote' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
    'updateIngredientStock' : IDL.Func([IDL.Nat, IDL.Nat], [], []),
    'updateLeadStatus' : IDL.Func([IDL.Nat, LeadStatus], [IDL.Bool], []),
    'updateMenuItem' : IDL.Func(
        [
          IDL.Nat,
          IDL.Text,
          IDL.Nat,
          IDL.Nat,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Vec(BowlSize),
          IDL.Vec(LinkedIngredient),
          IDL.Text,
        ],
        [],
        [],
      ),
    'updateOrder' : IDL.Func(
        [IDL.Nat, IDL.Opt(DeliveryStatus), IDL.Opt(IDL.Nat), IDL.Opt(IDL.Text)],
        [Result_1],
        [],
      ),
    'updateOrderDeliveryNotes' : IDL.Func([IDL.Nat, IDL.Text], [], []),
    'updateOrderDeliveryStatus' : IDL.Func([IDL.Nat, DeliveryStatus], [], []),
    'updateOrderStatus' : IDL.Func([IDL.Nat, OrderStatus], [], []),
    'updateReviewStatus' : IDL.Func([IDL.Text, ReviewStatus], [Result], []),
    'updateRider' : IDL.Func([IDL.Nat, IDL.Text, IDL.Text, IDL.Text], [], []),
    'updateSubscriptionPlan' : IDL.Func(
        [IDL.Nat, IDL.Text, IDL.Nat, IDL.Nat, IDL.Nat, IDL.Text],
        [],
        [],
      ),
    'updateSubscriptionStatus' : IDL.Func(
        [
          IDL.Principal,
          IDL.Variant({ 'active' : IDL.Null, 'expired' : IDL.Null }),
        ],
        [],
        [],
      ),
    'updateUserProfile' : IDL.Func([UserProfile], [], []),
    'updateUserProfileByAdmin' : IDL.Func([IDL.Principal, UserProfile], [], []),
    'validateCoupon' : IDL.Func([IDL.Text], [Coupon], ['query']),
  });
};

export const init = ({ IDL }) => { return []; };