/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export type DeliveryType = { 'scheduled' : Time } |
  { 'instant' : null };
export interface Ingredient {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'quantityInStock' : bigint,
  'name' : string,
  'unit' : string,
}
export interface MenuItemIngredient {
  'menuItemName' : string,
  'ingredientId' : bigint,
  'quantityPerOrder' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : Principal,
  'deliveryType' : { 'scheduled' : Time } |
    { 'instant' : null },
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'saladName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type PlanType = { 'monthly' : null } |
  { 'weekly' : null };
export interface Subscription {
  'status' : { 'active' : null } |
    { 'expired' : null },
  'saladsRemaining' : bigint,
  'user' : Principal,
  'planType' : { 'monthly' : null } |
    { 'weekly' : null },
  'startDate' : Time,
}
export type Time = bigint;
export interface UserProfile {
  'age' : bigint,
  'heightCm' : bigint,
  'dietaryPreferences' : Array<string>,
  'name' : string,
  'email' : string,
  'weightKg' : bigint,
  'dietaryRestrictions' : Array<string>,
  'address' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export type LeadStatus = { 'new_' : null } |
  { 'contacted' : null } |
  { 'converted' : null };
export interface MenuItem {
  'id' : bigint,
  'name' : string,
  'price' : bigint,
  'calories' : bigint,
  'protein' : bigint,
  'ingredients' : Array<string>,
  'tags' : Array<string>,
  'enabled' : boolean,
}

export interface Lead {
  'id' : bigint,
  'name' : string,
  'mobile' : string,
  'date' : Time,
  'status' : LeadStatus,
}
export interface _SERVICE {
  '_initializeAccessControlWithSecret' : ActorMethod<[string], undefined>,
  'addIngredient' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'createSubscription' : ActorMethod<[PlanType], undefined>,
  'getAllIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAllUsers' : ActorMethod<
    [],
    Array<{ 'principal' : Principal, 'profile' : UserProfile }>
  >,
  'getCallerSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLowStockIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getMenuItemIngredients' : ActorMethod<[string], Array<MenuItemIngredient>>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkIngredientToMenuItem' : ActorMethod<[string, bigint, bigint], undefined>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, bigint, DeliveryType],
    undefined
  >,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateIngredientStock' : ActorMethod<[bigint, bigint], undefined>,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateSubscriptionStatus' : ActorMethod<
    [Principal, { 'active' : null } | { 'expired' : null }],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveLead' : ActorMethod<[string, string], bigint>,
  'getAllLeads' : ActorMethod<[], Array<Lead>>,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], undefined>,
  'claimFirstAdminRole' : ActorMethod<[], undefined>,
  'hasAdminBeenClaimed' : ActorMethod<[], boolean>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'addMenuItem' : ActorMethod<[string, bigint, bigint, bigint, Array<string>, Array<string>], bigint>,
  'updateMenuItem' : ActorMethod<[bigint, string, bigint, bigint, bigint, Array<string>, Array<string>], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'toggleMenuItem' : ActorMethod<[bigint, boolean], undefined>,
  'createCoupon' : ActorMethod<[string, DiscountType, bigint, bigint], bigint>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'deleteCoupon' : ActorMethod<[bigint], undefined>,
  'toggleCoupon' : ActorMethod<[bigint, boolean], undefined>,
  'validateCoupon' : ActorMethod<[string], Coupon>,
  'addRider' : ActorMethod<[string, string, string], bigint>,
  'updateRider' : ActorMethod<[bigint, string, string, string], undefined>,
  'deleteRider' : ActorMethod<[bigint], undefined>,
  'getAllRiders' : ActorMethod<[], Array<Rider>>,
  'createDelivery' : ActorMethod<[bigint, string, string, bigint, string], bigint>,
  'updateDeliveryStatus' : ActorMethod<[bigint, DeliveryStatus], undefined>,
  'assignRider' : ActorMethod<[bigint, bigint], undefined>,
  'bulkAssignRider' : ActorMethod<[Array<bigint>, bigint], undefined>,
  'updateDeliveryNote' : ActorMethod<[bigint, string], undefined>,
  'getAllDeliveries' : ActorMethod<[], Array<DeliveryRecord>>,
  'setUserVip' : ActorMethod<[Principal, boolean], undefined>,
  'addUserNote' : ActorMethod<[Principal, string], bigint>,
  'deleteUserNote' : ActorMethod<[Principal, bigint], undefined>,
  'getUserMeta' : ActorMethod<[Principal], UserMeta>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'updateUserProfileByAdmin' : ActorMethod<[Principal, UserProfile], undefined>,

}

export type DiscountType = { 'percentage' : null } | { 'flat' : null };
export interface Coupon {
  'id' : bigint,
  'code' : string,
  'discountType' : DiscountType,
  'discountValue' : bigint,
  'expiryDate' : bigint,
  'isActive' : boolean,
}

export type DeliveryStatus = { 'preparing' : null } | { 'ready' : null } | { 'outForDelivery' : null } | { 'delivered' : null };
export interface Rider { 'id' : bigint, 'name' : string, 'mobile' : string, 'area' : string }
export interface UserNote { 'id': bigint, 'text': string, 'createdAt': bigint }
export interface UserMeta { 'isVip': boolean, 'notes': Array<UserNote> }

export interface DeliveryRecord {
  'id' : bigint,
  'orderId' : bigint,
  'customerName' : string,
  'address' : string,
  'deliveryTime' : bigint,
  'status' : DeliveryStatus,
  'riderId' : [] | [bigint],
  'notes' : string,
}

export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];