/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface BowlSize {
  'calories' : bigint,
  'size' : string,
  'price' : bigint,
  'protein' : bigint,
}
export interface Coupon {
  'id' : bigint,
  'discountValue' : bigint,
  'expiryDate' : Time,
  'code' : string,
  'discountType' : DiscountType,
  'isActive' : boolean,
}
export interface DeliveryRecord {
  'id' : bigint,
  'customerName' : string,
  'status' : DeliveryStatus,
  'riderId' : [] | [bigint],
  'deliveryTime' : Time,
  'orderId' : bigint,
  'address' : string,
  'notes' : string,
}
export type DeliveryStatus = { 'preparing' : null } |
  { 'outForDelivery' : null } |
  { 'delivered' : null } |
  { 'ready' : null };
export type DeliveryType = { 'scheduled' : Time } |
  { 'instant' : null };
export type DiscountType = { 'flat' : null } |
  { 'percentage' : null };
export interface Ingredient {
  'id' : bigint,
  'lowStockThreshold' : bigint,
  'quantityInStock' : bigint,
  'name' : string,
  'unit' : string,
}
export interface Lead {
  'id' : bigint,
  'status' : LeadStatus,
  'date' : Time,
  'name' : string,
  'mobile' : string,
}
export type LeadStatus = { 'new' : null } |
  { 'contacted' : null } |
  { 'converted' : null };
export interface LinkedIngredient {
  'quantityGrams' : bigint,
  'ingredientId' : bigint,
}
export interface MenuItem {
  'id' : bigint,
  'calories' : bigint,
  'name' : string,
  'tags' : Array<string>,
  'linkedIngredients' : Array<LinkedIngredient>,
  'sizes' : Array<BowlSize>,
  'enabled' : boolean,
  'imageUrl' : string,
  'price' : bigint,
  'ingredients' : Array<string>,
  'protein' : bigint,
}
export interface MenuItemIngredient {
  'menuItemName' : string,
  'ingredientId' : bigint,
  'quantityPerOrder' : bigint,
}
export interface Order {
  'id' : bigint,
  'status' : OrderStatus,
  'createdAt' : Time,
  'user' : Principal,
  'deliveryNotes' : string,
  'deliveryStatus' : DeliveryStatus,
  'assignedRiderId' : [] | [bigint],
  'deliveryTime' : [] | [Time],
  'deliveryType' : { 'scheduled' : Time } |
    { 'instant' : null },
  'totalAmount' : bigint,
  'items' : Array<OrderItem>,
}
export interface OrderItem {
  'saladName' : string,
  'quantity' : bigint,
  'price' : bigint,
}
export type OrderStatus = { 'pending' : null } |
  { 'delivered' : null } |
  { 'confirmed' : null };
export type Result = { 'ok' : Review } |
  { 'err' : string };
export type Result_1 = { 'ok' : Order } |
  { 'err' : string };
export type Result_2 = { 'ok' : bigint } |
  { 'err' : string };
export type Result_3 = { 'ok' : null } |
  { 'err' : string };
export interface Review {
  'id' : string,
  'status' : ReviewStatus,
  'userName' : string,
  'date' : bigint,
  'comment' : string,
  'rating' : bigint,
}
export type ReviewStatus = { 'pending' : null } |
  { 'approved' : null } |
  { 'rejected' : null };
export interface Rider {
  'id' : bigint,
  'area' : string,
  'name' : string,
  'mobile' : string,
}
export interface Subscription {
  'status' : { 'active' : null } |
    { 'expired' : null },
  'saladsRemaining' : bigint,
  'planId' : bigint,
  'expiryDate' : Time,
  'user' : Principal,
  'planName' : string,
  'startDate' : Time,
}
export interface SubscriptionPlan {
  'id' : bigint,
  'totalMeals' : bigint,
  'name' : string,
  'description' : string,
  'validityDays' : bigint,
  'price' : bigint,
}
export type Time = bigint;
export interface UserMeta { 'notes' : Array<UserNote>, 'isVip' : boolean }
export interface UserNote { 'id' : bigint, 'createdAt' : Time, 'text' : string }
export interface UserProfile {
  'age' : bigint,
  'heightCm' : bigint,
  'dietaryPreferences' : Array<string>,
  'name' : string,
  'email' : string,
  'weightKg' : bigint,
  'dietaryRestrictions' : Array<string>,
  'address' : string,
  'mobile' : string,
}
export type UserRole = { 'admin' : null } |
  { 'user' : null } |
  { 'guest' : null };
export interface _SERVICE {
  '_initializeAccessControl' : ActorMethod<[], undefined>,
  'addIngredient' : ActorMethod<[string, string, bigint, bigint], bigint>,
  'addMenuItem' : ActorMethod<
    [
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
      Array<BowlSize>,
      Array<LinkedIngredient>,
      string,
    ],
    bigint
  >,
  'addRider' : ActorMethod<[string, string, string], bigint>,
  'addUserNote' : ActorMethod<[Principal, string], bigint>,
  'assignCallerUserRole' : ActorMethod<[Principal, UserRole], undefined>,
  'assignOrderRider' : ActorMethod<[bigint, bigint], undefined>,
  'assignRider' : ActorMethod<[bigint, bigint], undefined>,
  'bulkAssignRider' : ActorMethod<[Array<bigint>, bigint], undefined>,
  'claimFirstAdminRole' : ActorMethod<[], undefined>,
  'createCoupon' : ActorMethod<[string, DiscountType, bigint, Time], bigint>,
  'createDelivery' : ActorMethod<
    [bigint, string, string, Time, string],
    bigint
  >,
  'createLead' : ActorMethod<[string, string], bigint>,
  'createReview' : ActorMethod<[string, bigint, string], Result>,
  'createSubscription' : ActorMethod<[bigint], undefined>,
  'createSubscriptionPlan' : ActorMethod<
    [string, bigint, bigint, bigint, string],
    bigint
  >,
  'deleteCoupon' : ActorMethod<[bigint], undefined>,
  'deleteMenuItem' : ActorMethod<[bigint], undefined>,
  'deleteReview' : ActorMethod<[string], Result_3>,
  'deleteRider' : ActorMethod<[bigint], undefined>,
  'deleteSubscriptionPlan' : ActorMethod<[bigint], undefined>,
  'deleteUser' : ActorMethod<[Principal], undefined>,
  'deleteUserNote' : ActorMethod<[Principal, bigint], undefined>,
  'getAllCoupons' : ActorMethod<[], Array<Coupon>>,
  'getAllDeliveries' : ActorMethod<[], Array<DeliveryRecord>>,
  'getAllIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getAllMenuItems' : ActorMethod<[], Array<MenuItem>>,
  'getAllOrders' : ActorMethod<[], Array<Order>>,
  'getAllReviews' : ActorMethod<[], Array<Review>>,
  'getAllRiders' : ActorMethod<[], Array<Rider>>,
  'getAllSubscriptionPlans' : ActorMethod<[], Array<SubscriptionPlan>>,
  'getAllSubscriptions' : ActorMethod<[], Array<Subscription>>,
  'getAllUsers' : ActorMethod<
    [],
    Array<{ 'principal' : Principal, 'profile' : UserProfile }>
  >,
  'getApprovedReviews' : ActorMethod<[], Array<Review>>,
  'getCallerSubscription' : ActorMethod<[], [] | [Subscription]>,
  'getCallerUserProfile' : ActorMethod<[], [] | [UserProfile]>,
  'getCallerUserRole' : ActorMethod<[], UserRole>,
  'getLeads' : ActorMethod<[], Array<Lead>>,
  'getLowStockIngredients' : ActorMethod<[], Array<Ingredient>>,
  'getMenuItemIngredients' : ActorMethod<[string], Array<MenuItemIngredient>>,
  'getUserMeta' : ActorMethod<[Principal], UserMeta>,
  'getUserOrders' : ActorMethod<[], Array<Order>>,
  'getUserProfile' : ActorMethod<[Principal], [] | [UserProfile]>,
  'hasAdminBeenClaimed' : ActorMethod<[], boolean>,
  'isCallerAdmin' : ActorMethod<[], boolean>,
  'linkIngredientToMenuItem' : ActorMethod<[string, bigint, bigint], undefined>,
  'placeOrder' : ActorMethod<
    [Array<OrderItem>, bigint, DeliveryType],
    Result_2
  >,
  'registerUser' : ActorMethod<[UserProfile], undefined>,
  'saveCallerUserProfile' : ActorMethod<[UserProfile], undefined>,
  'saveUserProfile' : ActorMethod<[UserProfile], undefined>,
  'setUserVip' : ActorMethod<[Principal, boolean], undefined>,
  'toggleCoupon' : ActorMethod<[bigint, boolean], undefined>,
  'toggleMenuItem' : ActorMethod<[bigint, boolean], undefined>,
  'updateDeliveryNote' : ActorMethod<[bigint, string], undefined>,
  'updateDeliveryStatus' : ActorMethod<[bigint, DeliveryStatus], undefined>,
  'updateIngredientStock' : ActorMethod<[bigint, bigint], undefined>,
  'updateLeadStatus' : ActorMethod<[bigint, LeadStatus], boolean>,
  'updateMenuItem' : ActorMethod<
    [
      bigint,
      string,
      bigint,
      bigint,
      bigint,
      Array<string>,
      Array<string>,
      Array<BowlSize>,
      Array<LinkedIngredient>,
      string,
    ],
    undefined
  >,
  'updateOrder' : ActorMethod<
    [bigint, [] | [DeliveryStatus], [] | [bigint], [] | [string]],
    Result_1
  >,
  'updateOrderDeliveryNotes' : ActorMethod<[bigint, string], undefined>,
  'updateOrderDeliveryStatus' : ActorMethod<
    [bigint, DeliveryStatus],
    undefined
  >,
  'updateOrderStatus' : ActorMethod<[bigint, OrderStatus], undefined>,
  'updateReviewStatus' : ActorMethod<[string, ReviewStatus], Result>,
  'updateRider' : ActorMethod<[bigint, string, string, string], undefined>,
  'updateSubscriptionPlan' : ActorMethod<
    [bigint, string, bigint, bigint, bigint, string],
    undefined
  >,
  'updateSubscriptionStatus' : ActorMethod<
    [Principal, { 'active' : null } | { 'expired' : null }],
    undefined
  >,
  'updateUserProfile' : ActorMethod<[UserProfile], undefined>,
  'updateUserProfileByAdmin' : ActorMethod<[Principal, UserProfile], undefined>,
  'validateCoupon' : ActorMethod<[string], Coupon>,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];