/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface Subscription {
    status: Variant_active_expired;
    saladsRemaining: bigint;
    user: Principal;
    planType: Variant_monthly_weekly;
    startDate: Time;
}
export type Time = bigint;
export interface Ingredient {
    id: bigint;
    lowStockThreshold: bigint;
    quantityInStock: bigint;
    name: string;
    unit: string;
}
export interface OrderItem {
    saladName: string;
    quantity: bigint;
    price: bigint;
}
export interface MenuItemIngredient {
    menuItemName: string;
    ingredientId: bigint;
    quantityPerOrder: bigint;
}
export type LeadStatus = {
    __kind__: "new_";
    new_: null;
} | {
    __kind__: "contacted";
    contacted: null;
} | {
    __kind__: "converted";
    converted: null;
};
export interface Lead {
    id: bigint;
    name: string;
    mobile: string;
    date: bigint;
    status: LeadStatus;
}

export type DiscountType = { __kind__: "percentage"; percentage: null } | { __kind__: "flat"; flat: null };
export interface Coupon {
    id: bigint;
    code: string;
    discountType: DiscountType;
    discountValue: bigint;
    expiryDate: bigint;
    isActive: boolean;
}
export interface MenuItem {
    id: bigint;
    name: string;
    price: bigint;
    calories: bigint;
    protein: bigint;
    ingredients: Array<string>;
    tags: Array<string>;
    enabled: boolean;
}

export enum DeliveryStatus {
    preparing = 'preparing',
    ready = 'ready',
    outForDelivery = 'outForDelivery',
    delivered = 'delivered',
}
export interface Rider {
    id: bigint;
    name: string;
    mobile: string;
    area: string;
}
export interface DeliveryRecord {
    id: bigint;
    orderId: bigint;
    customerName: string;
    address: string;
    deliveryTime: bigint;
    status: DeliveryStatus;
    riderId: bigint | null;
    notes: string;
}
export type DeliveryType = {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
};
export interface Order {
    id: bigint;
    status: OrderStatus;
    createdAt: Time;
    user: Principal;
    deliveryType: {
        __kind__: "scheduled";
        scheduled: Time;
    } | {
        __kind__: "instant";
        instant: null;
    };
    totalAmount: bigint;
    items: Array<OrderItem>;
}
export interface UserProfile {
    age: bigint;
    heightCm: bigint;
    dietaryPreferences: Array<string>;
    name: string;
    email: string;
    weightKg: bigint;
    dietaryRestrictions: Array<string>;
    address: string;
    mobile: string;
}
export enum OrderStatus {
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_expired {
    active = "active",
    expired = "expired"
}
export enum Variant_monthly_weekly {
    monthly = "monthly",
    weekly = "weekly"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addIngredient(name: string, unit: string, quantityInStock: bigint, lowStockThreshold: bigint): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    createSubscription(planType: PlanType): Promise<void>;
    getAllIngredients(): Promise<Array<Ingredient>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAllUsers(): Promise<Array<{
        principal: Principal;
        profile: UserProfile;
    }>>;
    getCallerSubscription(): Promise<Subscription | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLowStockIngredients(): Promise<Array<Ingredient>>;
    getMenuItemIngredients(menuItemName: string): Promise<Array<MenuItemIngredient>>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    isCallerAdmin(): Promise<boolean>;
    linkIngredientToMenuItem(menuItemName: string, ingredientId: bigint, quantityPerOrder: bigint): Promise<void>;
    placeOrder(items: Array<OrderItem>, totalAmount: bigint, deliveryType: DeliveryType): Promise<void>;
    registerUser(profile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserProfile(profile: UserProfile): Promise<void>;
    updateIngredientStock(id: bigint, newQuantity: bigint): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    updateSubscriptionStatus(user: Principal, status: Variant_active_expired): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
    saveLead(name: string, mobile: string): Promise<bigint>;
    getAllLeads(): Promise<Lead[]>;
    updateLeadStatus(id: bigint, status: LeadStatus): Promise<void>;
    hasAdminBeenClaimed(): Promise<boolean>;
    claimFirstAdminRole(): Promise<void>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    addMenuItem(name: string, price: bigint, calories: bigint, protein: bigint, ingredients: Array<string>, tags: Array<string>): Promise<bigint>;
    updateMenuItem(id: bigint, name: string, price: bigint, calories: bigint, protein: bigint, ingredients: Array<string>, tags: Array<string>): Promise<void>;
    deleteMenuItem(id: bigint): Promise<void>;
    toggleMenuItem(id: bigint, enabled: boolean): Promise<void>;
    addRider(name: string, mobile: string, area: string): Promise<bigint>;
    updateRider(id: bigint, name: string, mobile: string, area: string): Promise<void>;
    deleteRider(id: bigint): Promise<void>;
    getAllRiders(): Promise<Rider[]>;
    createDelivery(orderId: bigint, customerName: string, address: string, deliveryTime: bigint, notes: string): Promise<bigint>;
    updateDeliveryStatus(id: bigint, status: DeliveryStatus): Promise<void>;
    assignRider(deliveryId: bigint, riderId: bigint): Promise<void>;
    bulkAssignRider(deliveryIds: bigint[], riderId: bigint): Promise<void>;
    updateDeliveryNote(id: bigint, notes: string): Promise<void>;
    getAllDeliveries(): Promise<DeliveryRecord[]>;
    setUserVip(user: any, isVip: boolean): Promise<void>;
    addUserNote(user: any, text: string): Promise<bigint>;
    deleteUserNote(user: any, noteId: bigint): Promise<void>;
    getUserMeta(user: any): Promise<{ isVip: boolean; notes: Array<{ id: bigint; text: string; createdAt: bigint }> }>;
    deleteUser(user: any): Promise<void>;
    updateUserProfileByAdmin(user: any, profile: UserProfile): Promise<void>;
    createCoupon(code: string, discountType: DiscountType, discountValue: bigint, expiryDate: bigint): Promise<bigint>;
    getAllCoupons(): Promise<Coupon[]>;
    deleteCoupon(id: bigint): Promise<void>;
    toggleCoupon(id: bigint, isActive: boolean): Promise<void>;
    validateCoupon(code: string): Promise<Coupon>;
}
import type { DeliveryType as _DeliveryType, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, PlanType as _PlanType, Subscription as _Subscription, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addIngredient(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIngredient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIngredient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async createSubscription(arg0: PlanType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(to_candid_PlanType_n3(this._uploadFile, this._downloadFile, arg0));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(to_candid_PlanType_n3(this._uploadFile, this._downloadFile, arg0));
            return result;
        }
    }
    async getAllIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n11(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<{
        principal: Principal;
        profile: UserProfile;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getCallerSubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSubscription();
                return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSubscription();
            return from_candid_opt_n16(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n18(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockIngredients();
            return result;
        }
    }
    async getMenuItemIngredients(arg0: string): Promise<Array<MenuItemIngredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemIngredients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemIngredients(arg0);
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n17(this._uploadFile, this._downloadFile, result);
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkIngredientToMenuItem(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkIngredientToMenuItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkIngredientToMenuItem(arg0, arg1, arg2);
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: bigint, arg2: DeliveryType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_DeliveryType_n20(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_DeliveryType_n20(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0);
            return result;
        }
    }
    async updateIngredientStock(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredientStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredientStock(arg0, arg1);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n22(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n22(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: Principal, arg1: Variant_active_expired): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_variant_n24(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_variant_n24(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
    async saveLead(name: string, mobile: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.saveLead(name, mobile);
                return result as bigint;
            } catch (e) {
                this.processError(e);
            }
        }
        const result = await this.actor.saveLead(name, mobile);
        return result as bigint;
    }
    async getAllLeads(): Promise<Lead[]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllLeads();
                return result as Lead[];
            } catch (e) {
                this.processError(e);
            }
        }
        const result = await this.actor.getAllLeads();
        return result as Lead[];
    }
    async updateLeadStatus(id: bigint, status: LeadStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(id, status);
                return result as void;
            } catch (e) {
                this.processError(e);
            }
        }
        const result = await this.actor.updateLeadStatus(id, status);
        return result as void;
    }
    async hasAdminBeenClaimed(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAdminBeenClaimed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAdminBeenClaimed();
            return result;
        }
    }
    async claimFirstAdminRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdminRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdminRole();
            return result;
        }
    }
    async getAllMenuItems(): Promise<MenuItem[]> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result as MenuItem[];
            } catch (e) { this.processError(e); }
        }
        return await this.actor.getAllMenuItems() as MenuItem[];
    }
    async addMenuItem(name: string, price: bigint, calories: bigint, protein: bigint, ingredients: string[], tags: string[]): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(name, price, calories, protein, ingredients, tags);
                return result as bigint;
            } catch (e) { this.processError(e); }
        }
        return await this.actor.addMenuItem(name, price, calories, protein, ingredients, tags) as bigint;
    }
    async updateMenuItem(id: bigint, name: string, price: bigint, calories: bigint, protein: bigint, ingredients: string[], tags: string[]): Promise<void> {
        if (this.processError) {
            try { await this.actor.updateMenuItem(id, name, price, calories, protein, ingredients, tags); return; } catch (e) { this.processError(e); }
        }
        await this.actor.updateMenuItem(id, name, price, calories, protein, ingredients, tags);
    }
    async deleteMenuItem(id: bigint): Promise<void> {
        if (this.processError) {
            try { await this.actor.deleteMenuItem(id); return; } catch (e) { this.processError(e); }
        }
        await this.actor.deleteMenuItem(id);
    }
    async toggleMenuItem(id: bigint, enabled: boolean): Promise<void> {
        if (this.processError) {
            try { await this.actor.toggleMenuItem(id, enabled); return; } catch (e) { this.processError(e); }
        }
        await this.actor.toggleMenuItem(id, enabled);
    }
    async createCoupon(code: string, discountType: DiscountType, discountValue: bigint, expiryDate: bigint): Promise<bigint> {
        const dt = discountType.__kind__ === "percentage" ? { percentage: null } : { flat: null };
        if (this.processError) {
            try { return await this.actor.createCoupon(code, dt, discountValue, expiryDate); } catch (e) { this.processError(e); throw new Error("unreachable"); }
        }
        return await this.actor.createCoupon(code, dt, discountValue, expiryDate);
    }
    async getAllCoupons(): Promise<Coupon[]> {
        const raw = this.processError
            ? await (async () => { try { return await this.actor.getAllCoupons(); } catch (e) { this.processError!(e); throw new Error("unreachable"); } })()
            : await this.actor.getAllCoupons();
        return raw.map((c: any) => ({
            id: c.id,
            code: c.code,
            discountType: 'percentage' in c.discountType ? { __kind__: "percentage" as const, percentage: null } : { __kind__: "flat" as const, flat: null },
            discountValue: c.discountValue,
            expiryDate: c.expiryDate,
            isActive: c.isActive,
        }));
    }
    async deleteCoupon(id: bigint): Promise<void> {
        if (this.processError) {
            try { await this.actor.deleteCoupon(id); return; } catch (e) { this.processError(e); }
        }
        await this.actor.deleteCoupon(id);
    }
    async toggleCoupon(id: bigint, isActive: boolean): Promise<void> {
        if (this.processError) {
            try { await this.actor.toggleCoupon(id, isActive); return; } catch (e) { this.processError(e); }
        }
        await this.actor.toggleCoupon(id, isActive);
    }
    async validateCoupon(code: string): Promise<Coupon> {
        const raw: any = this.processError
            ? await (async () => { try { return await this.actor.validateCoupon(code); } catch (e) { this.processError!(e); throw new Error("unreachable"); } })()
            : await this.actor.validateCoupon(code);
        return {
            id: raw.id,
            code: raw.code,
            discountType: 'percentage' in raw.discountType ? { __kind__: "percentage" as const, percentage: null } : { __kind__: "flat" as const, flat: null },
            discountValue: raw.discountValue,
            expiryDate: raw.expiryDate,
            isActive: raw.isActive,
        };
    }

    async addRider(name: string, mobile: string, area: string): Promise<bigint> {
        if (this.processError) { try { return await this.actor.addRider(name, mobile, area) as bigint; } catch(e) { this.processError(e); throw new Error('unreachable'); } }
        return await this.actor.addRider(name, mobile, area) as bigint;
    }
    async updateRider(id: bigint, name: string, mobile: string, area: string): Promise<void> {
        if (this.processError) { try { await this.actor.updateRider(id, name, mobile, area); return; } catch(e) { this.processError(e); } }
        await this.actor.updateRider(id, name, mobile, area);
    }
    async deleteRider(id: bigint): Promise<void> {
        if (this.processError) { try { await this.actor.deleteRider(id); return; } catch(e) { this.processError(e); } }
        await this.actor.deleteRider(id);
    }
    async getAllRiders(): Promise<Rider[]> {
        const raw: any[] = this.processError
            ? await (async () => { try { return await this.actor.getAllRiders(); } catch(e) { this.processError!(e); throw new Error('unreachable'); } })()
            : await this.actor.getAllRiders() as any[];
        return raw.map((r: any) => ({ id: r.id, name: r.name, mobile: r.mobile, area: r.area }));
    }
    async createDelivery(orderId: bigint, customerName: string, address: string, deliveryTime: bigint, notes: string): Promise<bigint> {
        if (this.processError) { try { return await this.actor.createDelivery(orderId, customerName, address, deliveryTime, notes) as bigint; } catch(e) { this.processError(e); throw new Error('unreachable'); } }
        return await this.actor.createDelivery(orderId, customerName, address, deliveryTime, notes) as bigint;
    }
    async updateDeliveryStatus(id: bigint, status: DeliveryStatus): Promise<void> {
        const candid: any = status === DeliveryStatus.preparing ? { preparing: null } : status === DeliveryStatus.ready ? { ready: null } : status === DeliveryStatus.outForDelivery ? { outForDelivery: null } : { delivered: null };
        if (this.processError) { try { await this.actor.updateDeliveryStatus(id, candid); return; } catch(e) { this.processError(e); } }
        await this.actor.updateDeliveryStatus(id, candid);
    }
    async assignRider(deliveryId: bigint, riderId: bigint): Promise<void> {
        if (this.processError) { try { await this.actor.assignRider(deliveryId, riderId); return; } catch(e) { this.processError(e); } }
        await this.actor.assignRider(deliveryId, riderId);
    }
    async bulkAssignRider(deliveryIds: bigint[], riderId: bigint): Promise<void> {
        if (this.processError) { try { await this.actor.bulkAssignRider(deliveryIds, riderId); return; } catch(e) { this.processError(e); } }
        await this.actor.bulkAssignRider(deliveryIds, riderId);
    }
    async updateDeliveryNote(id: bigint, notes: string): Promise<void> {
        if (this.processError) { try { await this.actor.updateDeliveryNote(id, notes); return; } catch(e) { this.processError(e); } }
        await this.actor.updateDeliveryNote(id, notes);
    }
    async getAllDeliveries(): Promise<DeliveryRecord[]> {
        const raw: any[] = this.processError
            ? await (async () => { try { return await this.actor.getAllDeliveries(); } catch(e) { this.processError!(e); throw new Error('unreachable'); } })()
            : await this.actor.getAllDeliveries() as any[];
        return raw.map((d: any) => ({
            id: d.id, orderId: d.orderId, customerName: d.customerName,
            address: d.address, deliveryTime: d.deliveryTime,
            status: 'preparing' in d.status ? DeliveryStatus.preparing : 'ready' in d.status ? DeliveryStatus.ready : 'outForDelivery' in d.status ? DeliveryStatus.outForDelivery : DeliveryStatus.delivered,
            riderId: d.riderId.length > 0 ? d.riderId[0] : null,
            notes: d.notes,
        }));
    }
    async setUserVip(user: any, isVip: boolean): Promise<void> {
        if (this.processError) { try { await this.actor.setUserVip(user, isVip); return; } catch(e) { this.processError(e); } }
        await this.actor.setUserVip(user, isVip);
    }
    async addUserNote(user: any, text: string): Promise<bigint> {
        if (this.processError) { try { return await this.actor.addUserNote(user, text); } catch(e) { this.processError(e); throw e; } }
        return await this.actor.addUserNote(user, text) as bigint;
    }
    async deleteUserNote(user: any, noteId: bigint): Promise<void> {
        if (this.processError) { try { await this.actor.deleteUserNote(user, noteId); return; } catch(e) { this.processError(e); } }
        await this.actor.deleteUserNote(user, noteId);
    }
    async getUserMeta(user: any): Promise<{ isVip: boolean; notes: Array<{ id: bigint; text: string; createdAt: bigint }> }> {
        const raw: any = this.processError
            ? await (async () => { try { return await this.actor.getUserMeta(user); } catch(e) { this.processError!(e); throw new Error("unreachable"); } })()
            : await this.actor.getUserMeta(user);
        return { isVip: raw.isVip, notes: (raw.notes as any[]).map((n: any) => ({ id: n.id, text: n.text, createdAt: n.createdAt })) };
    }
    async deleteUser(user: any): Promise<void> {
        if (this.processError) { try { await this.actor.deleteUser(user); return; } catch(e) { this.processError(e); } }
        await this.actor.deleteUser(user);
    }
    async updateUserProfileByAdmin(user: any, profile: UserProfile): Promise<void> {
        const p: any = { name: profile.name, mobile: profile.mobile, email: profile.email, address: profile.address, heightCm: profile.heightCm, weightKg: profile.weightKg, age: profile.age, dietaryPreferences: profile.dietaryPreferences, dietaryRestrictions: profile.dietaryRestrictions };
        if (this.processError) { try { await this.actor.updateUserProfileByAdmin(user, p); return; } catch(e) { this.processError(e); } }
        await this.actor.updateUserProfileByAdmin(user, p);
    }
}
function from_candid_OrderStatus_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n9(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n7(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n12(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n13(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n12(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        expired: null;
    };
    saladsRemaining: bigint;
    user: Principal;
    planType: {
        monthly: null;
    } | {
        weekly: null;
    };
    startDate: _Time;
}): {
    status: Variant_active_expired;
    saladsRemaining: bigint;
    user: Principal;
    planType: Variant_monthly_weekly;
    startDate: Time;
} {
    return {
        status: from_candid_variant_n14(_uploadFile, _downloadFile, value.status),
        saladsRemaining: value.saladsRemaining,
        user: value.user,
        planType: from_candid_variant_n15(_uploadFile, _downloadFile, value.planType),
        startDate: value.startDate
    };
}
function from_candid_record_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _OrderStatus;
    createdAt: _Time;
    user: Principal;
    deliveryType: {
        scheduled: _Time;
    } | {
        instant: null;
    };
    totalAmount: bigint;
    items: Array<_OrderItem>;
}): {
    id: bigint;
    status: OrderStatus;
    createdAt: Time;
    user: Principal;
    deliveryType: {
        __kind__: "scheduled";
        scheduled: Time;
    } | {
        __kind__: "instant";
        instant: null;
    };
    totalAmount: bigint;
    items: Array<OrderItem>;
} {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n8(_uploadFile, _downloadFile, value.status),
        createdAt: value.createdAt,
        user: value.user,
        deliveryType: from_candid_variant_n10(_uploadFile, _downloadFile, value.deliveryType),
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: _Time;
} | {
    instant: null;
}): {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
} {
    return "scheduled" in value ? {
        __kind__: "scheduled",
        scheduled: value.scheduled
    } : "instant" in value ? {
        __kind__: "instant",
        instant: value.instant
    } : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
}): Variant_active_expired {
    return "active" in value ? Variant_active_expired.active : "expired" in value ? Variant_active_expired.expired : value;
}
function from_candid_variant_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    monthly: null;
} | {
    weekly: null;
}): Variant_monthly_weekly {
    return "monthly" in value ? Variant_monthly_weekly.monthly : "weekly" in value ? Variant_monthly_weekly.weekly : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_vec_n11(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n12(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n6(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryType_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): _DeliveryType {
    return to_candid_variant_n21(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n23(_uploadFile, _downloadFile, value);
}
function to_candid_PlanType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: PlanType): _PlanType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
}): {
    scheduled: _Time;
} | {
    instant: null;
} {
    return value.__kind__ === "scheduled" ? {
        scheduled: value.scheduled
    } : value.__kind__ === "instant" ? {
        instant: value.instant
    } : value;
}
function to_candid_variant_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_expired): {
    active: null;
} | {
    expired: null;
} {
    return value == Variant_active_expired.active ? {
        active: null
    } : value == Variant_active_expired.expired ? {
        expired: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_monthly_weekly): {
    monthly: null;
} | {
    weekly: null;
} {
    return value == Variant_monthly_weekly.monthly ? {
        monthly: null
    } : value == Variant_monthly_weekly.weekly ? {
        weekly: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
