/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Actor, HttpAgent, type HttpAgentOptions, type ActorConfig, type Agent, type ActorSubclass } from "@icp-sdk/core/agent";
import type { Principal } from "@icp-sdk/core/principal";
import { idlFactory, type _SERVICE } from "./declarations/backend.did";
export interface Some<T> {
    __kind__: "Some";
    value: T;
}
export interface None {
    __kind__: "None";
}
export type Option<T> = Some<T> | None;
function some<T>(value: T): Some<T> {
    return {
        __kind__: "Some",
        value: value
    };
}
function none(): None {
    return {
        __kind__: "None"
    };
}
function isNone<T>(option: Option<T>): option is None {
    return option.__kind__ === "None";
}
function isSome<T>(option: Option<T>): option is Some<T> {
    return option.__kind__ === "Some";
}
function unwrap<T>(option: Option<T>): T {
    if (isNone(option)) {
        throw new Error("unwrap: none");
    }
    return option.value;
}
function candid_some<T>(value: T): [T] {
    return [
        value
    ];
}
function candid_none<T>(): [] {
    return [];
}
function record_opt_to_undefined<T>(arg: T | null): T | undefined {
    return arg == null ? undefined : arg;
}
export class ExternalBlob {
    _blob?: Uint8Array<ArrayBuffer> | null;
    directURL: string;
    onProgress?: (percentage: number) => void = undefined;
    private constructor(directURL: string, blob: Uint8Array<ArrayBuffer> | null){
        if (blob) {
            this._blob = blob;
        }
        this.directURL = directURL;
    }
    static fromURL(url: string): ExternalBlob {
        return new ExternalBlob(url, null);
    }
    static fromBytes(blob: Uint8Array<ArrayBuffer>): ExternalBlob {
        const url = URL.createObjectURL(new Blob([
            new Uint8Array(blob)
        ], {
            type: 'application/octet-stream'
        }));
        return new ExternalBlob(url, blob);
    }
    public async getBytes(): Promise<Uint8Array<ArrayBuffer>> {
        if (this._blob) {
            return this._blob;
        }
        const response = await fetch(this.directURL);
        const blob = await response.blob();
        this._blob = new Uint8Array(await blob.arrayBuffer());
        return this._blob;
    }
    public getDirectURL(): string {
        return this.directURL;
    }
    public withUploadProgress(onProgress: (percentage: number) => void): ExternalBlob {
        this.onProgress = onProgress;
        return this;
    }
}
export interface DeliveryRecord {
    id: bigint;
    customerName: string;
    status: DeliveryStatus;
    riderId?: bigint;
    deliveryTime: Time;
    orderId: bigint;
    address: string;
    notes: string;
}
export type Time = bigint;
export interface Coupon {
    id: bigint;
    discountValue: bigint;
    expiryDate: Time;
    code: string;
    discountType: DiscountType;
    isActive: boolean;
}
export interface OrderItem {
    saladName: string;
    quantity: bigint;
    price: bigint;
}
export interface Rider {
    id: bigint;
    area: string;
    name: string;
    mobile: string;
}
export interface MenuItemIngredient {
    menuItemName: string;
    ingredientId: bigint;
    quantityPerOrder: bigint;
}
export type Result_1 = {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
};
export type Result_Order = {
    __kind__: "ok";
    ok: Order;
} | {
    __kind__: "err";
    err: string;
};
export interface Order {
    id: bigint;
    status: OrderStatus;
    createdAt: Time;
    user: Principal;
    deliveryType: {
        __kind__: "scheduled";
        scheduled: Time;
    } | {
        __kind__: "instant";
        instant: null;
    };
    totalAmount: bigint;
    items: Array<OrderItem>;
}
export interface Subscription {
    status: Variant_active_expired;
    saladsRemaining: bigint;
    user: Principal;
    planId: bigint;
    planName: string;
    startDate: Time;
    expiryDate: Time;
}
export interface SubscriptionPlan {
    id: bigint;
    name: string;
    totalMeals: bigint;
    price: bigint;
    validityDays: bigint;
    description: string;
}
export interface MenuItem {
    id: bigint;
    calories: bigint;
    name: string;
    tags: Array<string>;
    enabled: boolean;
    price: bigint;
    ingredients: Array<string>;
    protein: bigint;
}
export interface UserNote {
    id: bigint;
    createdAt: Time;
    text: string;
}
export type Result = {
    __kind__: "ok";
    ok: Review;
} | {
    __kind__: "err";
    err: string;
};
export interface Lead {
    id: bigint;
    status: LeadStatus;
    date: Time;
    name: string;
    mobile: string;
}
export interface UserMeta {
    notes: Array<UserNote>;
    isVip: boolean;
}
export interface Ingredient {
    id: bigint;
    lowStockThreshold: bigint;
    quantityInStock: bigint;
    name: string;
    unit: string;
}
export type DeliveryType = {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
};
export interface UserProfile {
    age: bigint;
    heightCm: bigint;
    dietaryPreferences: Array<string>;
    name: string;
    email: string;
    weightKg: bigint;
    dietaryRestrictions: Array<string>;
    address: string;
    mobile: string;
}
export interface Review {
    id: string;
    status: ReviewStatus;
    userName: string;
    date: bigint;
    comment: string;
    rating: bigint;
}
export enum DeliveryStatus {
    preparing = "preparing",
    outForDelivery = "outForDelivery",
    delivered = "delivered",
    ready = "ready"
}
export enum DiscountType {
    flat = "flat",
    percentage = "percentage"
}
export enum LeadStatus {
    new_ = "new",
    contacted = "contacted",
    converted = "converted"
}
export enum OrderStatus {
    pending = "pending",
    delivered = "delivered",
    confirmed = "confirmed"
}
export enum PlanType {
    monthly = "monthly",
    weekly = "weekly"
}
export enum ReviewStatus {
    pending = "pending",
    approved = "approved",
    rejected = "rejected"
}
export enum UserRole {
    admin = "admin",
    user = "user",
    guest = "guest"
}
export enum Variant_active_expired {
    active = "active",
    expired = "expired"
}
export interface backendInterface {
    _initializeAccessControlWithSecret(userSecret: string): Promise<void>;
    addIngredient(name: string, unit: string, quantityInStock: bigint, lowStockThreshold: bigint): Promise<bigint>;
    addMenuItem(name: string, price: bigint, calories: bigint, protein: bigint, ingredients: Array<string>, tags: Array<string>): Promise<bigint>;
    addRider(name: string, mobile: string, area: string): Promise<bigint>;
    addUserNote(user: Principal, text: string): Promise<bigint>;
    assignCallerUserRole(user: Principal, role: UserRole): Promise<void>;
    assignRider(deliveryId: bigint, riderId: bigint): Promise<void>;
    bulkAssignRider(deliveryIds: Array<bigint>, riderId: bigint): Promise<void>;
    claimFirstAdminRole(): Promise<void>;
    createCoupon(code: string, discountType: DiscountType, discountValue: bigint, expiryDate: Time): Promise<bigint>;
    createDelivery(orderId: bigint, customerName: string, address: string, deliveryTime: Time, notes: string): Promise<bigint>;
    createLead(name: string, mobile: string): Promise<bigint>;
    createReview(userName: string, rating: bigint, comment: string): Promise<Result>;
    createSubscription(planId: bigint): Promise<void>;
    deleteCoupon(id: bigint): Promise<void>;
    deleteMenuItem(id: bigint): Promise<void>;
    deleteReview(id: string): Promise<Result_1>;
    deleteRider(id: bigint): Promise<void>;
    deleteUser(user: Principal): Promise<void>;
    deleteUserNote(user: Principal, noteId: bigint): Promise<void>;
    getAllCoupons(): Promise<Array<Coupon>>;
    getAllDeliveries(): Promise<Array<DeliveryRecord>>;
    getAllIngredients(): Promise<Array<Ingredient>>;
    getAllMenuItems(): Promise<Array<MenuItem>>;
    getAllOrders(): Promise<Array<Order>>;
    getAllReviews(): Promise<Array<Review>>;
    getAllRiders(): Promise<Array<Rider>>;
    getAllSubscriptionPlans(): Promise<Array<SubscriptionPlan>>;
    createSubscriptionPlan(name: string, totalMeals: bigint, price: bigint, validityDays: bigint, description: string): Promise<bigint>;
    updateSubscriptionPlan(id: bigint, name: string, totalMeals: bigint, price: bigint, validityDays: bigint, description: string): Promise<void>;
    deleteSubscriptionPlan(id: bigint): Promise<void>;
    getAllSubscriptions(): Promise<Array<Subscription>>;
    getAllUsers(): Promise<Array<{
        principal: Principal;
        profile: UserProfile;
    }>>;
    getApprovedReviews(): Promise<Array<Review>>;
    getCallerSubscription(): Promise<Subscription | null>;
    getCallerUserProfile(): Promise<UserProfile | null>;
    getCallerUserRole(): Promise<UserRole>;
    getLeads(): Promise<Array<Lead>>;
    getLowStockIngredients(): Promise<Array<Ingredient>>;
    getMenuItemIngredients(menuItemName: string): Promise<Array<MenuItemIngredient>>;
    getUserMeta(user: Principal): Promise<UserMeta>;
    getUserOrders(): Promise<Array<Order>>;
    getUserProfile(user: Principal): Promise<UserProfile | null>;
    hasAdminBeenClaimed(): Promise<boolean>;
    isCallerAdmin(): Promise<boolean>;
    linkIngredientToMenuItem(menuItemName: string, ingredientId: bigint, quantityPerOrder: bigint): Promise<void>;
    placeOrder(items: Array<OrderItem>, totalAmount: bigint, deliveryType: DeliveryType): Promise<void>;
    registerUser(profile: UserProfile): Promise<void>;
    saveCallerUserProfile(profile: UserProfile): Promise<void>;
    saveUserProfile(profile: UserProfile): Promise<void>;
    setUserVip(user: Principal, isVip: boolean): Promise<void>;
    toggleCoupon(id: bigint, isActive: boolean): Promise<void>;
    toggleMenuItem(id: bigint, enabled: boolean): Promise<void>;
    updateDeliveryNote(id: bigint, notes: string): Promise<void>;
    updateDeliveryStatus(id: bigint, status: DeliveryStatus): Promise<void>;
    updateIngredientStock(id: bigint, newQuantity: bigint): Promise<void>;
    updateLeadStatus(id: bigint, status: LeadStatus): Promise<boolean>;
    updateMenuItem(id: bigint, name: string, price: bigint, calories: bigint, protein: bigint, ingredients: Array<string>, tags: Array<string>): Promise<void>;
    updateOrder(orderId: bigint, deliveryStatus: DeliveryStatus | null, assignedRiderId: bigint | null, deliveryNotes: string | null): Promise<Result_Order>;
    updateOrderDeliveryNotes(orderId: bigint, notes: string): Promise<void>;
    updateOrderDeliveryStatus(orderId: bigint, deliveryStatus: DeliveryStatus): Promise<void>;
    assignOrderRider(orderId: bigint, riderId: bigint): Promise<void>;
    updateOrderStatus(orderId: bigint, status: OrderStatus): Promise<void>;
    updateReviewStatus(id: string, status: ReviewStatus): Promise<Result>;
    updateRider(id: bigint, name: string, mobile: string, area: string): Promise<void>;
    updateSubscriptionStatus(user: Principal, status: Variant_active_expired): Promise<void>;
    updateUserProfile(profile: UserProfile): Promise<void>;
    updateUserProfileByAdmin(user: Principal, profile: UserProfile): Promise<void>;
    validateCoupon(code: string): Promise<Coupon>;
}
import type { Coupon as _Coupon, DeliveryRecord as _DeliveryRecord, DeliveryStatus as _DeliveryStatus, DeliveryType as _DeliveryType, DiscountType as _DiscountType, Lead as _Lead, LeadStatus as _LeadStatus, Order as _Order, OrderItem as _OrderItem, OrderStatus as _OrderStatus, Result as _Result, Result_1 as _Result_1, Review as _Review, ReviewStatus as _ReviewStatus, Subscription as _Subscription, SubscriptionPlan as _SubscriptionPlan, Time as _Time, UserProfile as _UserProfile, UserRole as _UserRole } from "./declarations/backend.did.d.ts";
export class Backend implements backendInterface {
    constructor(private actor: ActorSubclass<_SERVICE>, private _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, private _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, private processError?: (error: unknown) => never){}
    async _initializeAccessControlWithSecret(arg0: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor._initializeAccessControlWithSecret(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor._initializeAccessControlWithSecret(arg0);
            return result;
        }
    }
    async addIngredient(arg0: string, arg1: string, arg2: bigint, arg3: bigint): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addIngredient(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addIngredient(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async addMenuItem(arg0: string, arg1: bigint, arg2: bigint, arg3: bigint, arg4: Array<string>, arg5: Array<string>): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addMenuItem(arg0, arg1, arg2, arg3, arg4, arg5);
            return result;
        }
    }
    async addRider(arg0: string, arg1: string, arg2: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addRider(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addRider(arg0, arg1, arg2);
            return result;
        }
    }
    async addUserNote(arg0: Principal, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.addUserNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.addUserNote(arg0, arg1);
            return result;
        }
    }
    async assignCallerUserRole(arg0: Principal, arg1: UserRole): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignCallerUserRole(arg0, to_candid_UserRole_n1(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignRider(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.assignRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.assignRider(arg0, arg1);
            return result;
        }
    }
    async bulkAssignRider(arg0: Array<bigint>, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.bulkAssignRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.bulkAssignRider(arg0, arg1);
            return result;
        }
    }
    async claimFirstAdminRole(): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.claimFirstAdminRole();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.claimFirstAdminRole();
            return result;
        }
    }
    async createCoupon(arg0: string, arg1: DiscountType, arg2: bigint, arg3: Time): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createCoupon(arg0, to_candid_DiscountType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createCoupon(arg0, to_candid_DiscountType_n3(this._uploadFile, this._downloadFile, arg1), arg2, arg3);
            return result;
        }
    }
    async createDelivery(arg0: bigint, arg1: string, arg2: string, arg3: Time, arg4: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createDelivery(arg0, arg1, arg2, arg3, arg4);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createDelivery(arg0, arg1, arg2, arg3, arg4);
            return result;
        }
    }
    async createLead(arg0: string, arg1: string): Promise<bigint> {
        if (this.processError) {
            try {
                const result = await this.actor.createLead(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createLead(arg0, arg1);
            return result;
        }
    }
    async createReview(arg0: string, arg1: bigint, arg2: string): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.createReview(arg0, arg1, arg2);
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createReview(arg0, arg1, arg2);
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubscription(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.createSubscription(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.createSubscription(arg0);
            return result;
        }
    }
    async deleteCoupon(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteCoupon(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteCoupon(arg0);
            return result;
        }
    }
    async deleteMenuItem(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteMenuItem(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteMenuItem(arg0);
            return result;
        }
    }
    async deleteReview(arg0: string): Promise<Result_1> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteReview(arg0);
                return from_candid_Result_1_n13(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteReview(arg0);
            return from_candid_Result_1_n13(this._uploadFile, this._downloadFile, result);
        }
    }
    async deleteRider(arg0: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteRider(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteRider(arg0);
            return result;
        }
    }
    async deleteUser(arg0: Principal): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUser(arg0);
            return result;
        }
    }
    async deleteUserNote(arg0: Principal, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.deleteUserNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.deleteUserNote(arg0, arg1);
            return result;
        }
    }
    async getAllCoupons(): Promise<Array<Coupon>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllCoupons();
                return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllCoupons();
            return from_candid_vec_n15(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllDeliveries(): Promise<Array<DeliveryRecord>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllDeliveries();
                return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllDeliveries();
            return from_candid_vec_n20(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllIngredients();
            return result;
        }
    }
    async getAllMenuItems(): Promise<Array<MenuItem>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllMenuItems();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllMenuItems();
            return result;
        }
    }
    async getAllOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllReviews();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllReviews();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllRiders(): Promise<Array<Rider>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllRiders();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllRiders();
            return result;
        }
    }
    async getAllSubscriptionPlans(): Promise<Array<SubscriptionPlan>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptionPlans();
                return from_candid_vec_SubscriptionPlan(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptionPlans();
            return from_candid_vec_SubscriptionPlan(this._uploadFile, this._downloadFile, result);
        }
    }
    async createSubscriptionPlan(name: string, totalMeals: bigint, price: bigint, validityDays: bigint, description: string): Promise<bigint> {
        if (this.processError) {
            try {
                return await this.actor.createSubscriptionPlan(name, totalMeals, price, validityDays, description);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.createSubscriptionPlan(name, totalMeals, price, validityDays, description);
        }
    }
    async updateSubscriptionPlan(id: bigint, name: string, totalMeals: bigint, price: bigint, validityDays: bigint, description: string): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.updateSubscriptionPlan(id, name, totalMeals, price, validityDays, description);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.updateSubscriptionPlan(id, name, totalMeals, price, validityDays, description);
        }
    }
    async deleteSubscriptionPlan(id: bigint): Promise<void> {
        if (this.processError) {
            try {
                return await this.actor.deleteSubscriptionPlan(id);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            return await this.actor.deleteSubscriptionPlan(id);
        }
    }
    async getAllSubscriptions(): Promise<Array<Subscription>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllSubscriptions();
                return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllSubscriptions();
            return from_candid_vec_n33(this._uploadFile, this._downloadFile, result);
        }
    }
    async getAllUsers(): Promise<Array<{
        principal: Principal;
        profile: UserProfile;
    }>> {
        if (this.processError) {
            try {
                const result = await this.actor.getAllUsers();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getAllUsers();
            return result;
        }
    }
    async getApprovedReviews(): Promise<Array<Review>> {
        if (this.processError) {
            try {
                const result = await this.actor.getApprovedReviews();
                return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getApprovedReviews();
            return from_candid_vec_n32(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerSubscription(): Promise<Subscription | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerSubscription();
                return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerSubscription();
            return from_candid_opt_n38(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserProfile(): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserProfile();
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserProfile();
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async getCallerUserRole(): Promise<UserRole> {
        if (this.processError) {
            try {
                const result = await this.actor.getCallerUserRole();
                return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getCallerUserRole();
            return from_candid_UserRole_n40(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLeads(): Promise<Array<Lead>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLeads();
                return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLeads();
            return from_candid_vec_n42(this._uploadFile, this._downloadFile, result);
        }
    }
    async getLowStockIngredients(): Promise<Array<Ingredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getLowStockIngredients();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getLowStockIngredients();
            return result;
        }
    }
    async getMenuItemIngredients(arg0: string): Promise<Array<MenuItemIngredient>> {
        if (this.processError) {
            try {
                const result = await this.actor.getMenuItemIngredients(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getMenuItemIngredients(arg0);
            return result;
        }
    }
    async getUserMeta(arg0: Principal): Promise<UserMeta> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserMeta(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserMeta(arg0);
            return result;
        }
    }
    async getUserOrders(): Promise<Array<Order>> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserOrders();
                return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserOrders();
            return from_candid_vec_n26(this._uploadFile, this._downloadFile, result);
        }
    }
    async getUserProfile(arg0: Principal): Promise<UserProfile | null> {
        if (this.processError) {
            try {
                const result = await this.actor.getUserProfile(arg0);
                return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.getUserProfile(arg0);
            return from_candid_opt_n39(this._uploadFile, this._downloadFile, result);
        }
    }
    async hasAdminBeenClaimed(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.hasAdminBeenClaimed();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.hasAdminBeenClaimed();
            return result;
        }
    }
    async isCallerAdmin(): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.isCallerAdmin();
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.isCallerAdmin();
            return result;
        }
    }
    async linkIngredientToMenuItem(arg0: string, arg1: bigint, arg2: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.linkIngredientToMenuItem(arg0, arg1, arg2);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.linkIngredientToMenuItem(arg0, arg1, arg2);
            return result;
        }
    }
    async placeOrder(arg0: Array<OrderItem>, arg1: bigint, arg2: DeliveryType): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.placeOrder(arg0, arg1, to_candid_DeliveryType_n47(this._uploadFile, this._downloadFile, arg2));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.placeOrder(arg0, arg1, to_candid_DeliveryType_n47(this._uploadFile, this._downloadFile, arg2));
            return result;
        }
    }
    async registerUser(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.registerUser(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.registerUser(arg0);
            return result;
        }
    }
    async saveCallerUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveCallerUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveCallerUserProfile(arg0);
            return result;
        }
    }
    async saveUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.saveUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.saveUserProfile(arg0);
            return result;
        }
    }
    async setUserVip(arg0: Principal, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.setUserVip(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.setUserVip(arg0, arg1);
            return result;
        }
    }
    async toggleCoupon(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleCoupon(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleCoupon(arg0, arg1);
            return result;
        }
    }
    async toggleMenuItem(arg0: bigint, arg1: boolean): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.toggleMenuItem(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.toggleMenuItem(arg0, arg1);
            return result;
        }
    }
    async updateDeliveryNote(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryNote(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryNote(arg0, arg1);
            return result;
        }
    }
    async updateDeliveryStatus(arg0: bigint, arg1: DeliveryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateDeliveryStatus(arg0, to_candid_DeliveryStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateIngredientStock(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateIngredientStock(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateIngredientStock(arg0, arg1);
            return result;
        }
    }
    async updateLeadStatus(arg0: bigint, arg1: LeadStatus): Promise<boolean> {
        if (this.processError) {
            try {
                const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n51(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateLeadStatus(arg0, to_candid_LeadStatus_n51(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateMenuItem(arg0: bigint, arg1: string, arg2: bigint, arg3: bigint, arg4: bigint, arg5: Array<string>, arg6: Array<string>): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateMenuItem(arg0, arg1, arg2, arg3, arg4, arg5, arg6);
            return result;
        }
    }
    async updateOrderStatus(arg0: bigint, arg1: OrderStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n53(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateOrderStatus(arg0, to_candid_OrderStatus_n53(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateOrderDeliveryStatus(arg0: bigint, arg1: DeliveryStatus): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).updateOrderDeliveryStatus(arg0, to_candid_DeliveryStatus_n49(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).updateOrderDeliveryStatus(arg0, to_candid_DeliveryStatus_n49(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async assignOrderRider(arg0: bigint, arg1: bigint): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).assignOrderRider(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).assignOrderRider(arg0, arg1);
            return result;
        }
    }
    async updateOrderDeliveryNotes(arg0: bigint, arg1: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await (this.actor as any).updateOrderDeliveryNotes(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).updateOrderDeliveryNotes(arg0, arg1);
            return result;
        }
    }
    async updateOrder(arg0: bigint, arg1: DeliveryStatus | null, arg2: bigint | null, arg3: string | null): Promise<Result_Order> {
        const candid_arg1: [] | [any] = arg1 !== null ? [to_candid_DeliveryStatus_n49(this._uploadFile, this._downloadFile, arg1)] : [];
        const candid_arg2: [] | [bigint] = arg2 !== null ? [arg2] : [];
        const candid_arg3: [] | [string] = arg3 !== null ? [arg3] : [];
        if (this.processError) {
            try {
                const result = await (this.actor as any).updateOrder(arg0, candid_arg1, candid_arg2, candid_arg3);
                return from_candid_Result_Order(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await (this.actor as any).updateOrder(arg0, candid_arg1, candid_arg2, candid_arg3);
            return from_candid_Result_Order(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateReviewStatus(arg0: string, arg1: ReviewStatus): Promise<Result> {
        if (this.processError) {
            try {
                const result = await this.actor.updateReviewStatus(arg0, to_candid_ReviewStatus_n55(this._uploadFile, this._downloadFile, arg1));
                return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateReviewStatus(arg0, to_candid_ReviewStatus_n55(this._uploadFile, this._downloadFile, arg1));
            return from_candid_Result_n5(this._uploadFile, this._downloadFile, result);
        }
    }
    async updateRider(arg0: bigint, arg1: string, arg2: string, arg3: string): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateRider(arg0, arg1, arg2, arg3);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateRider(arg0, arg1, arg2, arg3);
            return result;
        }
    }
    async updateSubscriptionStatus(arg0: Principal, arg1: Variant_active_expired): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_variant_n57(this._uploadFile, this._downloadFile, arg1));
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateSubscriptionStatus(arg0, to_candid_variant_n57(this._uploadFile, this._downloadFile, arg1));
            return result;
        }
    }
    async updateUserProfile(arg0: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfile(arg0);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfile(arg0);
            return result;
        }
    }
    async updateUserProfileByAdmin(arg0: Principal, arg1: UserProfile): Promise<void> {
        if (this.processError) {
            try {
                const result = await this.actor.updateUserProfileByAdmin(arg0, arg1);
                return result;
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.updateUserProfileByAdmin(arg0, arg1);
            return result;
        }
    }
    async validateCoupon(arg0: string): Promise<Coupon> {
        if (this.processError) {
            try {
                const result = await this.actor.validateCoupon(arg0);
                return from_candid_Coupon_n16(this._uploadFile, this._downloadFile, result);
            } catch (e) {
                this.processError(e);
                throw new Error("unreachable");
            }
        } else {
            const result = await this.actor.validateCoupon(arg0);
            return from_candid_Coupon_n16(this._uploadFile, this._downloadFile, result);
        }
    }
}
function from_candid_Coupon_n16(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Coupon): Coupon {
    return from_candid_record_n17(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryRecord_n21(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryRecord): DeliveryRecord {
    return from_candid_record_n22(_uploadFile, _downloadFile, value);
}
function from_candid_DeliveryStatus_n23(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DeliveryStatus): DeliveryStatus {
    return from_candid_variant_n24(_uploadFile, _downloadFile, value);
}
function from_candid_DiscountType_n18(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _DiscountType): DiscountType {
    return from_candid_variant_n19(_uploadFile, _downloadFile, value);
}
function from_candid_LeadStatus_n45(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _LeadStatus): LeadStatus {
    return from_candid_variant_n46(_uploadFile, _downloadFile, value);
}
function from_candid_Lead_n43(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Lead): Lead {
    return from_candid_record_n44(_uploadFile, _downloadFile, value);
}
function from_candid_OrderStatus_n29(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _OrderStatus): OrderStatus {
    return from_candid_variant_n30(_uploadFile, _downloadFile, value);
}
function from_candid_Order_n27(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Order): Order {
    return from_candid_record_n28(_uploadFile, _downloadFile, value);
}
function from_candid_Result_1_n13(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result_1): Result_1 {
    return from_candid_variant_n14(_uploadFile, _downloadFile, value);
}
function from_candid_Result_n5(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Result): Result {
    return from_candid_variant_n6(_uploadFile, _downloadFile, value);
}
function from_candid_Result_Order(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: any): Result_Order {
    if ('ok' in value) {
        return { __kind__: 'ok', ok: from_candid_record_n28(_uploadFile, _downloadFile, value.ok) };
    } else {
        return { __kind__: 'err', err: value.err };
    }
}
function from_candid_ReviewStatus_n9(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _ReviewStatus): ReviewStatus {
    return from_candid_variant_n10(_uploadFile, _downloadFile, value);
}
function from_candid_Review_n7(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Review): Review {
    return from_candid_record_n8(_uploadFile, _downloadFile, value);
}
function from_candid_Subscription_n34(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _Subscription): Subscription {
    return from_candid_record_n35(_uploadFile, _downloadFile, value);
}
function from_candid_UserRole_n40(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _UserRole): UserRole {
    return from_candid_variant_n41(_uploadFile, _downloadFile, value);
}
function from_candid_opt_n25(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [bigint]): bigint | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_opt_n38(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_Subscription]): Subscription | null {
    return value.length === 0 ? null : from_candid_Subscription_n34(_uploadFile, _downloadFile, value[0]);
}
function from_candid_opt_n39(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: [] | [_UserProfile]): UserProfile | null {
    return value.length === 0 ? null : value[0];
}
function from_candid_record_n17(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    discountValue: bigint;
    expiryDate: _Time;
    code: string;
    discountType: _DiscountType;
    isActive: boolean;
}): {
    id: bigint;
    discountValue: bigint;
    expiryDate: Time;
    code: string;
    discountType: DiscountType;
    isActive: boolean;
} {
    return {
        id: value.id,
        discountValue: value.discountValue,
        expiryDate: value.expiryDate,
        code: value.code,
        discountType: from_candid_DiscountType_n18(_uploadFile, _downloadFile, value.discountType),
        isActive: value.isActive
    };
}
function from_candid_record_n22(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    customerName: string;
    status: _DeliveryStatus;
    riderId: [] | [bigint];
    deliveryTime: _Time;
    orderId: bigint;
    address: string;
    notes: string;
}): {
    id: bigint;
    customerName: string;
    status: DeliveryStatus;
    riderId?: bigint;
    deliveryTime: Time;
    orderId: bigint;
    address: string;
    notes: string;
} {
    return {
        id: value.id,
        customerName: value.customerName,
        status: from_candid_DeliveryStatus_n23(_uploadFile, _downloadFile, value.status),
        riderId: record_opt_to_undefined(from_candid_opt_n25(_uploadFile, _downloadFile, value.riderId)),
        deliveryTime: value.deliveryTime,
        orderId: value.orderId,
        address: value.address,
        notes: value.notes
    };
}
function from_candid_record_n28(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: any): Order {
    return {
        id: value.id,
        status: from_candid_OrderStatus_n29(_uploadFile, _downloadFile, value.status),
        deliveryStatus: value.deliveryStatus ? from_candid_DeliveryStatus_n23(_uploadFile, _downloadFile, value.deliveryStatus) : DeliveryStatus.preparing,
        assignedRiderId: value.assignedRiderId && value.assignedRiderId.length > 0 ? value.assignedRiderId[0] : undefined,
        deliveryTime: value.deliveryTime && value.deliveryTime.length > 0 ? value.deliveryTime[0] : undefined,
        deliveryNotes: value.deliveryNotes ?? "",
        createdAt: value.createdAt,
        user: value.user,
        deliveryType: from_candid_variant_n31(_uploadFile, _downloadFile, value.deliveryType),
        totalAmount: value.totalAmount,
        items: value.items
    };
}
function from_candid_record_n35(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    status: {
        active: null;
    } | {
        expired: null;
    };
    saladsRemaining: bigint;
    user: Principal;
    planId: bigint;
    planName: string;
    startDate: _Time;
    expiryDate: _Time;
}): {
    status: Variant_active_expired;
    saladsRemaining: bigint;
    user: Principal;
    planId: bigint;
    planName: string;
    startDate: Time;
    expiryDate: Time;
} {
    return {
        status: from_candid_variant_n36(_uploadFile, _downloadFile, value.status),
        saladsRemaining: value.saladsRemaining,
        user: value.user,
        planId: value.planId,
        planName: value.planName,
        startDate: value.startDate,
        expiryDate: value.expiryDate,
    };
}
function from_candid_record_n44(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: bigint;
    status: _LeadStatus;
    date: _Time;
    name: string;
    mobile: string;
}): {
    id: bigint;
    status: LeadStatus;
    date: Time;
    name: string;
    mobile: string;
} {
    return {
        id: value.id,
        status: from_candid_LeadStatus_n45(_uploadFile, _downloadFile, value.status),
        date: value.date,
        name: value.name,
        mobile: value.mobile
    };
}
function from_candid_record_n8(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    id: string;
    status: _ReviewStatus;
    userName: string;
    date: bigint;
    comment: string;
    rating: bigint;
}): {
    id: string;
    status: ReviewStatus;
    userName: string;
    date: bigint;
    comment: string;
    rating: bigint;
} {
    return {
        id: value.id,
        status: from_candid_ReviewStatus_n9(_uploadFile, _downloadFile, value.status),
        userName: value.userName,
        date: value.date,
        comment: value.comment,
        rating: value.rating
    };
}
function from_candid_variant_n10(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
}): ReviewStatus {
    return "pending" in value ? ReviewStatus.pending : "approved" in value ? ReviewStatus.approved : "rejected" in value ? ReviewStatus.rejected : value;
}
function from_candid_variant_n14(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: null;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: null;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: value.ok
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_variant_n19(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    flat: null;
} | {
    percentage: null;
}): DiscountType {
    return "flat" in value ? DiscountType.flat : "percentage" in value ? DiscountType.percentage : value;
}
function from_candid_variant_n24(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    preparing: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    ready: null;
}): DeliveryStatus {
    return "preparing" in value ? DeliveryStatus.preparing : "outForDelivery" in value ? DeliveryStatus.outForDelivery : "delivered" in value ? DeliveryStatus.delivered : "ready" in value ? DeliveryStatus.ready : value;
}
function from_candid_variant_n30(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
}): OrderStatus {
    return "pending" in value ? OrderStatus.pending : "delivered" in value ? OrderStatus.delivered : "confirmed" in value ? OrderStatus.confirmed : value;
}
function from_candid_variant_n31(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    scheduled: _Time;
} | {
    instant: null;
}): {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
} {
    return "scheduled" in value ? {
        __kind__: "scheduled",
        scheduled: value.scheduled
    } : "instant" in value ? {
        __kind__: "instant",
        instant: value.instant
    } : value;
}
function from_candid_variant_n36(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    active: null;
} | {
    expired: null;
}): Variant_active_expired {
    return "active" in value ? Variant_active_expired.active : "expired" in value ? Variant_active_expired.expired : value;
}
function from_candid_variant_n41(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
}): UserRole {
    return "admin" in value ? UserRole.admin : "user" in value ? UserRole.user : "guest" in value ? UserRole.guest : value;
}
function from_candid_variant_n46(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    new: null;
} | {
    contacted: null;
} | {
    converted: null;
}): LeadStatus {
    return "new" in value ? LeadStatus.new : "contacted" in value ? LeadStatus.contacted : "converted" in value ? LeadStatus.converted : value;
}
function from_candid_variant_n6(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    ok: _Review;
} | {
    err: string;
}): {
    __kind__: "ok";
    ok: Review;
} | {
    __kind__: "err";
    err: string;
} {
    return "ok" in value ? {
        __kind__: "ok",
        ok: from_candid_Review_n7(_uploadFile, _downloadFile, value.ok)
    } : "err" in value ? {
        __kind__: "err",
        err: value.err
    } : value;
}
function from_candid_vec_n15(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Coupon>): Array<Coupon> {
    return value.map((x)=>from_candid_Coupon_n16(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n20(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_DeliveryRecord>): Array<DeliveryRecord> {
    return value.map((x)=>from_candid_DeliveryRecord_n21(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n26(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Order>): Array<Order> {
    return value.map((x)=>from_candid_Order_n27(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n32(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Review>): Array<Review> {
    return value.map((x)=>from_candid_Review_n7(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n33(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Subscription>): Array<Subscription> {
    return value.map((x)=>from_candid_Subscription_n34(_uploadFile, _downloadFile, x));
}
function from_candid_vec_n42(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_Lead>): Array<Lead> {
    return value.map((x)=>from_candid_Lead_n43(_uploadFile, _downloadFile, x));
}
function from_candid_SubscriptionPlan(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: _SubscriptionPlan): SubscriptionPlan {
    return {
        id: value.id,
        name: value.name,
        totalMeals: value.totalMeals,
        price: value.price,
        validityDays: value.validityDays,
        description: value.description,
    };
}
function from_candid_vec_SubscriptionPlan(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Array<_SubscriptionPlan>): Array<SubscriptionPlan> {
    return value.map((x) => from_candid_SubscriptionPlan(_uploadFile, _downloadFile, x));
}
function to_candid_DeliveryStatus_n49(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): _DeliveryStatus {
    return to_candid_variant_n50(_uploadFile, _downloadFile, value);
}
function to_candid_DeliveryType_n47(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryType): _DeliveryType {
    return to_candid_variant_n48(_uploadFile, _downloadFile, value);
}
function to_candid_DiscountType_n3(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): _DiscountType {
    return to_candid_variant_n4(_uploadFile, _downloadFile, value);
}
function to_candid_LeadStatus_n51(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): _LeadStatus {
    return to_candid_variant_n52(_uploadFile, _downloadFile, value);
}
function to_candid_OrderStatus_n53(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): _OrderStatus {
    return to_candid_variant_n54(_uploadFile, _downloadFile, value);
}
function to_candid_ReviewStatus_n55(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): _ReviewStatus {
    return to_candid_variant_n56(_uploadFile, _downloadFile, value);
}
function to_candid_UserRole_n1(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): _UserRole {
    return to_candid_variant_n2(_uploadFile, _downloadFile, value);
}
function to_candid_variant_n2(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: UserRole): {
    admin: null;
} | {
    user: null;
} | {
    guest: null;
} {
    return value == UserRole.admin ? {
        admin: null
    } : value == UserRole.user ? {
        user: null
    } : value == UserRole.guest ? {
        guest: null
    } : value;
}
function to_candid_variant_n4(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DiscountType): {
    flat: null;
} | {
    percentage: null;
} {
    return value == DiscountType.flat ? {
        flat: null
    } : value == DiscountType.percentage ? {
        percentage: null
    } : value;
}
function to_candid_variant_n48(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: {
    __kind__: "scheduled";
    scheduled: Time;
} | {
    __kind__: "instant";
    instant: null;
}): {
    scheduled: _Time;
} | {
    instant: null;
} {
    return value.__kind__ === "scheduled" ? {
        scheduled: value.scheduled
    } : value.__kind__ === "instant" ? {
        instant: value.instant
    } : value;
}
function to_candid_variant_n50(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: DeliveryStatus): {
    preparing: null;
} | {
    outForDelivery: null;
} | {
    delivered: null;
} | {
    ready: null;
} {
    return value == DeliveryStatus.preparing ? {
        preparing: null
    } : value == DeliveryStatus.outForDelivery ? {
        outForDelivery: null
    } : value == DeliveryStatus.delivered ? {
        delivered: null
    } : value == DeliveryStatus.ready ? {
        ready: null
    } : value;
}
function to_candid_variant_n52(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: LeadStatus): {
    new: null;
} | {
    contacted: null;
} | {
    converted: null;
} {
    return value == LeadStatus.new ? {
        new_: null
    } : value == LeadStatus.contacted ? {
        contacted: null
    } : value == LeadStatus.converted ? {
        converted: null
    } : value;
}
function to_candid_variant_n54(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: OrderStatus): {
    pending: null;
} | {
    delivered: null;
} | {
    confirmed: null;
} {
    return value == OrderStatus.pending ? {
        pending: null
    } : value == OrderStatus.delivered ? {
        delivered: null
    } : value == OrderStatus.confirmed ? {
        confirmed: null
    } : value;
}
function to_candid_variant_n56(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: ReviewStatus): {
    pending: null;
} | {
    approved: null;
} | {
    rejected: null;
} {
    return value == ReviewStatus.pending ? {
        pending: null
    } : value == ReviewStatus.approved ? {
        approved: null
    } : value == ReviewStatus.rejected ? {
        rejected: null
    } : value;
}
function to_candid_variant_n57(_uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, value: Variant_active_expired): {
    active: null;
} | {
    expired: null;
} {
    return value == Variant_active_expired.active ? {
        active: null
    } : value == Variant_active_expired.expired ? {
        expired: null
    } : value;
}
export interface CreateActorOptions {
    agent?: Agent;
    agentOptions?: HttpAgentOptions;
    actorOptions?: ActorConfig;
    processError?: (error: unknown) => never;
}
export function createActor(canisterId: string, _uploadFile: (file: ExternalBlob) => Promise<Uint8Array>, _downloadFile: (file: Uint8Array) => Promise<ExternalBlob>, options: CreateActorOptions = {}): Backend {
    const agent = options.agent || HttpAgent.createSync({
        ...options.agentOptions
    });
    if (options.agent && options.agentOptions) {
        console.warn("Detected both agent and agentOptions passed to createActor. Ignoring agentOptions and proceeding with the provided agent.");
    }
    const actor = Actor.createActor<_SERVICE>(idlFactory, {
        agent,
        canisterId: canisterId,
        ...options.actorOptions
    });
    return new Backend(actor, _uploadFile, _downloadFile, options.processError);
}
